--[[
#-----------------------------------------------------------------------------#
----*					MTA DayZ: table_vehicles.lua    				*----
----* Original Author: Marwin W., Germany, Lower Saxony, Otterndorf		*----

----* This gamemode is being developed by L, CiBeR96, 1B0Y				*----
----* Type: CLIENT														*----
#-----------------------------------------------------------------------------#
]]

vehicleDataTable = {
-- [[ Weapons ]] --
{"M1911"},
{"Revolver"},
{"Makarov PM"},
{"Bizon PP-19 SD"},
{"G17"},
{"M9"},
{"Makarov SD"},
{"PDW"},
{"MP5A5"},
{"Lee Enfield"},
{"AK-74"},
{"AKS-74U"},
{"RPK"},
{"AKM"},
{"Sa58V CCO"},
{"Sa58V RCO"},
{"FN FAL"},
{"M24"},
{"DMR"},
{"M40A3"},
{"G36A CAMO"},
{"G36C"},
{"G36C CAMO"},
{"G36K CAMO"},
{"L85A2 RIS Holo"},
{"M16A2"},
{"M16A2 M203"},
{"M4A1"},
{"M16A4"},
{"CZ 550"},
{"SVD Dragunov"},
{"Mosin-Nagant"},
{"Winchester 1866"},
{"Double-barreled Shotgun"},
{"M1014"},
{"Remington 870"},
{"Compound Crossbow"},
{"Baseball Bat"},
{"Crowbar"},
{"Hatchet"},
{"Machete"},
{"Parachute"},
{"Grenade"},
{"Hunting Knife"},
{"Binoculars"},
{"Range Finder"},
{"Shovel"},
-- [[ Ammo ]] --
{"11.43x23mm Cartridge"},
{"9x18mm Cartridge"},
{"9x19mm Cartridge"},
{".303 British Cartridge"},
{"5.45x39mm Cartridge"},
{"7.62x39mm Cartridge"},
{"7.62x51mm Cartridge"},
{"5.56x45mm Cartridge"},
{".308 Winchester Cartridge"},
{"7.62x54mm Cartridge"},
{"1866 Slug"},
{"12 Gauge Pellet"},
{"Bolt"},
-- [[ Food / Drinks ]] --
{"Baked Beans"},
{"Pasta"},
{"Sardines"},
{"Frank & Beans"},
{"Can (Corn)"},
{"Can (Peas)"},
{"Can (Pork)"},
{"Can (Stew)"},
{"Can (Ravioli)"},
{"Can (Fruit)"},
{"Can (Chowder)"},
{"Pistachios"},
{"Trail Mix"},
{"MRE"},
{"Water Bottle"},
{"Soda Can (Pepsi)"},
{"Soda Can (Cola)"},
{"Soda Can (Mountain Dew)"},
{"Can (Milk)"},
-- [[ Items ]] --
{"Wood Pile"},
{"Bandage"},
{"Antibiotics"},
{"Epi-Pen"},
{"Road Flare"},
{"Empty Gas Canister"},
{"Full Gas Canister"},
{"Heat Pack"},
{"Painkiller"},
{"Morphine"},
{"Blood Bag"},
{"Blood Bag (Empty)"},
{"Transfusion Kit"},
{"Blood Test Kit"},
{"Wire Fence"},
{"Raw Meat"},
{"Tire"},
{"Engine"},
{"Tank Parts"},
{"Scrap Metal"},
{"Main Rotary Parts"},
{"Windscreen Glass"},
{"Tent"},
{"Box of Matches"},
{"Watch"},
{"GPS"},
{"Map"},
{"Toolbox"},
{"IR Goggles"},
{"NV Goggles"},
{"Cooked Meat"},
{"Radio Device"},
{"Compass"},
{"Camouflage Clothing"},
{"Civilian Clothing"},
{"Survivor Clothing"},
{"Survivor Clothing (Female)"},
{"Civilian Clothing (Female)"},
{"Ghillie Suit"},
{"Military collar"},
{"Africa collar"},
{"Gold collar"},
{"Silver collar"},
{"LS collar"},
{"Black Bandana (M)"},
{"Blue Bandana (M)"},
{"Green Bandana (M)"},
{"Red Bandana (M)"},
{"Black Bandana (H)"},
{"Blue Bandana (H)"},
{"Green Bandana (H)"},
{"Red Bandana (H)"},
{"Black Beret"},
{"Red Beret"},
{"Old Hat"},
{"Black Hat"},
{"Yellow Hat"},
{"Black Trucker"},
{"Blue Trucker"},
{"Green Trucker"},
{"Red Trucker"},
{"Yellow Trucker"},
{"Cow-Boy Hat"},
{"White Hat"},
{"Hockey Mask"},
{"Black Shoe"},
{"Sport Shoe"},
{"Brown Shoe"},
{"Biker Shoe"},
{"Blue Shoe"},
{"Red Shoe"},
{"Beach Shoe"},
{"Black Pants"},
{"Beige Pants"},
{"Gray Shorts"},
{"Blue Shorts"},
{"Blue Jeans"},
{"Green Jeans"},
{"Gray Pants"},
{"Yellow Pants"},
{"Blue Jogging"},
{"Gray Jogging"},
{"Military Pants"},
{"Beige Vest"},
{"Baseball Shirt"},
{"Baseball 2 Shirt"},
{"Red Vest"},
{"Grey Shirt"},
{"Green Vest"},
{"Hawai Shirt"},
{"Black Vest"},
{"Brown Vest"},
{"Biker Vest"},
{"Blue Shirt"},
{"Green 2 Vest"},
{"Number 5 Shirt"},
{"Monk Shirt"},
{"Dark Glasses"},
{"Square Glasses"},
{"Red Glasses"},
{"Helmet"},
{"MX Helmet"},
{"Empty Water Bottle"},
{"Empty Soda Can"},
{"Empty Tin Can"},
{"Broken Whiskey Bottle"},
{"Assault Pack (ACU)"},
{"ALICE Pack"},
{"British Assault Pack"},
{"Czech Vest Pouch"},
{"Backpack (Coyote)"},
{"Czech Backpack"},
{"Survival ACU"},
{"San Fierro Carrier Keycard"},
{"Area 69 Keycard"},
-- [[ Blueprints ]] --
{"M4 Blueprint"},
{"CZ 550 Blueprint"},
{"Winchester 1866 Blueprint"},
{"SPAZ-12 C. Shtgn. Blueprint"},
{"Sawn-Off Shtgn. Blueprint"},
{"AK-47 Blueprint"},
{"Lee Enfield Blueprint"},
{"Sporter 22 Blueprint"},
{"Mosin 9130 Blueprint"},
{"Crossbow Blueprint"},
{"SKS Blueprint"},
{"Blaze 95 D. R. Blueprint"},
{"Remington 870 Blueprint"},
{"FN FAL Blueprint"},
{"G36C Blueprint"},
{"Sa58V CCO Blueprint"},
{"SVD Dragunov Blueprint"},
{"DMR Blueprint"},
{"M1911 Blueprint"},
{"M9 SD Blueprint"},
{"PDW Blueprint"},
{"G17 Blueprint"},
{"MP5A5 Blueprint"},
{"Bizon PP-19 Blueprint"},
{"Revolver Blueprint"},
{"Desert Eagle Blueprint"},
{"Hunting Knife Blueprint"},
{"Hatchet Blueprint"},
{"Baseball Bat Blueprint"},
{"Shovel Blueprint"},
{"Golf Club Blueprint"},
{"Machete Blueprint"},
{"Crowbar Blueprint"},
{"Parachute Blueprint"},
{"Tear Gas Blueprint"},
{"Grenade Blueprint"},
{"Binoculars Blueprint"},
{".45 ACP Cartridge Blueprint"},
{"9x19mm SD Cartridge Blueprint"},
{"9x19mm Cartridge Blueprint"},
{"9x18mm Cartridge Blueprint"},
{"5.45x39mm Cartridge Blueprint"},
{"5.56x45mm Cartridge Blueprint"},
{"1866 Slug Blueprint"},
{"2Rnd. Slug Blueprint"},
{"12 Gauge Pellet Blueprint"},
{"9.3x62mm Cartridge Blueprint"},
{".303 British Cartridge Blueprint"},
{"Bolt Blueprint"},
{"Medic Kit Blueprint"},
{"Wire Fence Blueprint"},
{"Tent Blueprint"},
{"Camouflage Clthng. Blueprint"},
{"Survivor Clthng. Blueprint"},
{"Civilian Clthng. Blueprint"},
{"Ghillie Suit Blueprint"},
{"Road Flare Blueprint"},
{"Toolbox Blueprint"},
{"Radio Device Blueprint"},
{"IR Goggles Blueprint"},
{"NV Goggles Blueprint"},
{"Gun Barrel"},
{"Short Gun Barrel"},
{"Gun Stock"},
{"Thread"},
{"Cloth"},
{"Gun Powder"},
{"Mechanical Supplies"},
{"Cables"},
{"Nails"},
{"Sheet"},
{"Barbed Wire"},
{"Duct Tape"},
{"Glue"},
{"Drugs"},
{"Bandaid"},
{"Vitamins"},
{"Tissue"},
{"Small Box"},
{"String"},
{"Needle"},
{"Microchips"},
{"Optics"},
{"Sharp Metal"},
{"Handle"},
{"Wooden Stick"},
{"Hand Saw"},
{"Metal Plate"},
{"Metallic Stick"},
{"Small Casing"},

{"DIY (Wood)"},
{"DIY (Metal)"},
{"Log"},
{"Stone"},
{"Plank"},
{"RSJ"},
{"Metal Sheet"},
{"Metal Sheet (Rusted)"},
}

vehicleAddonsInfo = {
-- {Model, Wheels, Engine, TankParts, ScrapMetal, WindscreenGlass, RotaryParts, Name, ColsphereSize, Slots, Fuel,RealName, varName}

-- VEHICLES
{471,4,1,1,0,0,0,"ATV",2,50,30,"Quadbike","atv"},
{431,6,1,1,0,0,0,"Bus",5,50,100,"Bus","bus"},
{509,2,0,0,0,0,0,"Old Bike",2,0,0,"Bike","bike"},
{546,4,1,1,0,0,0,"GAZ",3,50,200,"Intruder","gaz"},
{433,8,1,1,0,0,0,"Military Offroad",4,50,200,"Barracks","militaryoffroad"},
{468,2,1,1,0,0,0,"Motorcycle",2,5,55,"Sanchez","motorcycle"},
{543,4,1,1,0,0,0,"Offroad Pickup Truck",3,50,100,"Sadler","pickupoffroad"},
{426,4,1,1,0,0,0,"Old Hatchback",3,50,50,"Premier","hatchback"},
{422,4,1,1,0,0,0,"Pickup Truck",3,50,200,"Bobcat","pickup"},
{418,4,4,1,0,0,0,"S1203 Van",3,50,60,"Moonbeam","svan"},
{400,4,1,1,0,0,0,"Skoda",3,75,200,"Landstalker","skoda"},
{531,4,1,1,0,0,0,"Tractor",3,50,100,"Tractor","tractor"},
{470,4,1,1,0,0,0,"UAZ",3,50,100,"Patriot","uaz"},
{455,6,1,1,0,0,0,"Ural Civilian",5,200,200,"Flatbed","uralcivilian"},
{490,4,1,1,0,0,0,"SUV",3,50,200,"FBI Rancher","suv"},
{478,6,1,1,0,0,0,"V3S Civilian",5,200,160,"Walton","v3scivilian"},

-- AIRCRAFT
{469,0,0,0,0,0,1,"AH6X Little Bird",7,20,1000,"Sparrow","ah6x"},
{417,0,0,0,0,0,1,"UH-1H Huey",7,50,1000,"Leviathan","huey"},
{487,0,0,0,0,0,1,"Mi-17",7,20,1000,"Maverick","mi17"},
{488,0,0,0,0,0,1,"MH6J",7,20,600,"News Chopper","mh6j"},
{511,2,0,0,0,0,2,"An-2 Biplane",7,100,400,"Beagle","an2biplane"},

-- BOATS
{453,0,1,0,0,0,0,"Fishing Boat",4,400,100,"Reefer","fishingboat"},
{595,0,1,0,0,0,0,"Small Boat",3,0,100,"Launch","smallboat"},
{473,0,1,0,0,0,0,"PBX",2,0,100,"Dinghy","pbx"},
}

vehicleFuelTable = {
-- {Model,MaxFuel}
-- VEHICLES
{471,30},
{431,100},
{509,0},
{546,200},
{433,200},
{468,55},
{543,100},
{426,50},
{422,200},
{418,60},
{400,200},
{531,100},
{470,100},
{455,200},
{490,200},
{478,160},

-- AIRCRAFT
{469,1000},
{417,1000},
{487,1000},
{488,600},
{511,400},

-- BOATS
{453,100},
{595,100},
{473,100}
}

vehicleFuelConsumption = {
-- {Model,ConsumptionPerMinute}
-- VEHICLES
{471,0.1},
{431,0.3},
{509,0},
{546,0.5},
{433,0.5},
{468,0.1},
{543,0.5},
{426,0.1},
{422,0.5},
{418,0.1},
{400,0.5},
{531,0.3},
{470,0.3},
{455,0.5},
{490,0.5},
{478,0.4},

-- AIRCRAFT
{469,3},
{417,3},
{487,3},
{488,2},
{511,1},

-- BOATS
{453,0.5},
{595,0.5},
{473,0.5}
}