--[[
#-----------------------------------------------------------------------------#
----*					MTA DayZ: loadskins.lua							*----
----* Original Author: Marwin W., Germany, Lower Saxony, Otterndorf		*----

----* This gamemode is being developed by L, CiBeR96, 1B0Y				*----
----* Type: CLIENT														*----
#-----------------------------------------------------------------------------#
]]

-- // Animals // --
animalTXD = engineLoadTXD(":DayZ/models/animals/txd/bear.txd")
engineImportTXD(animalTXD, 12)
animalDFF = engineLoadDFF(":DayZ/models/animals/dff/bear.dff", 12)
engineReplaceModel(animalDFF, 12)
animalTXD = engineLoadTXD(":DayZ/models/animals/txd/goat.txd")
engineImportTXD(animalTXD, 13)
animalDFF = engineLoadDFF(":DayZ/models/animals/dff/goat.dff", 13)
engineReplaceModel(animalDFF, 13)
animalTXD = engineLoadTXD(":DayZ/models/animals/txd/wolf.txd")
engineImportTXD(animalTXD, 14)
animalDFF = engineLoadDFF(":DayZ/models/animals/dff/wolf.dff", 14)
engineReplaceModel(animalDFF, 14)
animalTXD = engineLoadTXD(":DayZ/models/animals/txd/cow1.txd")
engineImportTXD(animalTXD, 15)
animalDFF = engineLoadDFF(":DayZ/models/animals/dff/cow1.dff", 15)
engineReplaceModel(animalDFF, 15)
animalTXD = engineLoadTXD(":DayZ/models/animals/txd/cow2.txd")
engineImportTXD(animalTXD, 16)
animalDFF = engineLoadDFF(":DayZ/models/animals/dff/cow2.dff", 16)
engineReplaceModel(animalDFF, 16)

-- // Vehicles // --
vehicleTXD = engineLoadTXD(":DayZ/models/vehicles/txd/uaz.txd")
engineImportTXD(vehicleTXD,470)
vehicleDFF = engineLoadDFF(":DayZ/models/vehicles/dff/uaz.dff", 470)
engineReplaceModel(vehicleDFF,470)


-- // Player Skins // --
-- Standard (Male)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/standard_male.txd")
engineImportTXD(snipertxd, 73)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/standard_male.dff", 73)
engineReplaceModel(sniperdff, 73)
-- Standard (Female)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/standard_female.txd")
engineImportTXD(snipertxd, 192)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/standard_female.dff", 192)
engineReplaceModel(sniperdff, 192)
-- Civilian (Male)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/civilian_male.txd")
engineImportTXD(snipertxd, 179)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/civilian_male.dff", 179)
engineReplaceModel(sniperdff, 179)
--Civilian (Female)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/civilian_female.txd")
engineImportTXD(snipertxd, 172)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/civilian_female.dff", 172)
engineReplaceModel(sniperdff, 172)
-- Ghillie Suit
snipertxd = engineLoadTXD(":DayZ/models/players/txd/ghilliesuit.txd")
engineImportTXD(snipertxd, 285)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/ghilliesuit.dff", 285)
engineReplaceModel(sniperdff, 285)
--Bandit 1 (Male)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/bandit1_male.txd")
engineImportTXD(snipertxd, 180)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/bandit1_male.dff", 180)
engineReplaceModel(sniperdff, 180)
-- Bandit 1 (Female)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/bandit1_female.txd")
engineImportTXD(snipertxd, 191)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/bandit1_female.dff", 191)
engineReplaceModel(sniperdff, 191)
--Bandit 2 (Male)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/bandit2_male.txd")
engineImportTXD(snipertxd, 288)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/bandit2_male.dff", 288)
engineReplaceModel(sniperdff, 288)
-- Bandit 2 (Female)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/bandit2_female.txd")
engineImportTXD(snipertxd, 211)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/bandit2_female.dff", 211)
engineReplaceModel(sniperdff, 211)
-- Hero (Male)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/hero_male.txd")
engineImportTXD(snipertxd, 210)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/hero_male.dff", 210)
engineReplaceModel(sniperdff, 210)
-- Army (Male)
snipertxd = engineLoadTXD(":DayZ/models/players/txd/army_male.txd")
engineImportTXD(snipertxd, 287)
sniperdff = engineLoadDFF(":DayZ/models/players/dff/army_male.dff", 287)
engineReplaceModel(sniperdff, 287)


-- // Items // --
itemTXD = engineLoadTXD(":DayZ/models/items/txd/army_clothes.txd")
engineImportTXD(itemTXD, 1247)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/army_clothes.dff", 1247)
engineReplaceModel(itemDFF, 1247)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/sniper_clothes.txd")
engineImportTXD(itemTXD, 1213)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/sniper_clothes.dff", 1213)
engineReplaceModel(itemDFF, 1213)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/civilian_clothes.txd")
engineImportTXD(itemTXD, 1241)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/civilian_clothes.dff", 1241)
engineReplaceModel(itemDFF, 1241)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/standard_clothes.txd")
engineImportTXD(itemTXD, 1577)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/standard_clothes.dff", 1577)
engineReplaceModel(itemDFF, 1577)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/beans_can.txd")
engineImportTXD(itemTXD, 2601)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/beans_can.dff", 2601)
engineReplaceModel(itemDFF, 2601)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/first_aid_kit.txd")
engineImportTXD(itemTXD, 2891)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/first_aid_kit.dff", 2891)
engineReplaceModel(itemDFF, 2891)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/heat_pack.txd")
engineImportTXD(itemTXD, 1576)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/heat_pack.dff", 1576)
engineReplaceModel(itemDFF, 1576)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/pain_killers.txd")
engineImportTXD(itemTXD, 2709)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/pain_killers.dff", 2709)
engineReplaceModel(itemDFF, 2709)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/pasta_can.txd")
engineImportTXD(itemTXD, 2770)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/pasta_can.dff", 2770)
engineReplaceModel(itemDFF, 2770)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/soda_can.txd")
engineImportTXD(itemTXD, 2647)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/soda_can.dff", 2647)
engineReplaceModel(itemDFF, 2647)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/water_bottle.txd")
engineImportTXD(itemTXD, 2683)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/water_bottle.dff", 2683)
engineReplaceModel(itemDFF, 2683)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/wirefence.txd")
engineImportTXD(itemTXD, 983)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/wirefence.dff", 983)
engineReplaceModel(itemDFF, 983)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/windscreenglass.txd")
engineImportTXD(itemTXD, 3104)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/windscreenglass.dff", 3104)
engineReplaceModel(itemDFF, 3104)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/pistol_ammo.txd")
engineImportTXD(itemTXD, 3013)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/pistol_ammo.dff", 3013)
engineReplaceModel(itemDFF, 3013)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/shotgun_ammo.txd")
engineImportTXD(itemTXD, 2358)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/shotgun_ammo.dff", 2358)
engineReplaceModel(itemDFF, 2358)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/smg_ammo.txd")
engineImportTXD(itemTXD, 2041)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/smg_ammo.dff", 2041)
engineReplaceModel(itemDFF, 2041)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/sniper_ammo.txd")
engineImportTXD(itemTXD, 2358)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/sniper_ammo.dff", 2358)
engineReplaceModel(itemDFF, 2358)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/assault_ammo.txd")
engineImportTXD(itemTXD, 1271)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/assault_ammo.dff", 1271)
engineReplaceModel(itemDFF, 1271)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_patrol.txd")
engineImportTXD(itemTXD, 3026)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_patrol.dff", 3026)
engineReplaceModel(itemDFF, 3026)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_assault.txd")
engineImportTXD(itemTXD, 1644)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_assault.dff", 1644)
engineReplaceModel(itemDFF, 1644)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_pouch.txd")
engineImportTXD(itemTXD, 1248)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_pouch.dff", 1248)
engineReplaceModel(itemDFF, 1248)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_alice.txd")
engineImportTXD(itemTXD, 2382)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_alice.dff", 2382)
engineReplaceModel(itemDFF, 2382)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_survival.txd")
engineImportTXD(itemTXD, 1314)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_survival.dff", 1314)
engineReplaceModel(itemDFF, 1314)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_british.txd")
engineImportTXD(itemTXD, 1318)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_british.dff", 1318)
engineReplaceModel(itemDFF, 1318)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_coyote.txd")
engineImportTXD(itemTXD, 1252)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_coyote.dff", 1252)
engineReplaceModel(itemDFF, 1252)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/backpack_czech.txd")
engineImportTXD(itemTXD, 1575)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/backpack_czech.dff", 1575)
engineReplaceModel(itemDFF, 1575)
itemTXD = engineLoadTXD(":DayZ/models/items/txd/tent.txd")
engineImportTXD(itemTXD, 3243)
itemDFF = engineLoadDFF(":DayZ/models/items/dff/tent.dff", 3243)
engineReplaceModel(itemDFF, 3243)
itemCOL = engineLoadCOL(":DayZ/models/items/dff/tent.col")
engineReplaceCOL(itemCOL,3243)


-- // Weapons // --
weaponTXD = engineLoadTXD(":DayZ/models/weapons/txd/binoculars.txd")
engineImportTXD(weaponTXD, 367)
weaponDFF = engineLoadDFF(":DayZ/models/weapons/dff/binoculars.dff", 367)
engineReplaceModel(weaponDFF, 367)
weaponTXD = engineLoadTXD(":DayZ/models/weapons/txd/hatchet.txd")
engineImportTXD(weaponTXD, 339)
weaponDFF = engineLoadDFF(":DayZ/models/weapons/dff/hatchet.dff", 339)
engineReplaceModel(weaponDFF, 339)
weaponTXD1 = engineLoadTXD(":DayZ/models/weapons/txd/fnfal.txd")
weaponDFF1 = engineLoadDFF(":DayZ/models/weapons/dff/fnfal.dff", 0)
weaponTXD2 = engineLoadTXD(":DayZ/models/weapons/txd/g36c.txd")
weaponDFF2 = engineLoadDFF(":DayZ/models/weapons/dff/g36c.dff", 0)
weaponTXD3 = engineLoadTXD(":DayZ/models/weapons/txd/crossbow.txd")
weaponDFF3 = engineLoadDFF(":DayZ/models/weapons/dff/crossbow.dff", 0)
weaponTXD4 = engineLoadTXD(":DayZ/models/weapons/txd/dmr.txd")
weaponDFF4 = engineLoadDFF(":DayZ/models/weapons/dff/dmr.dff", 0)
weaponTXD5 = engineLoadTXD(":DayZ/models/weapons/txd/dragunov.txd")
weaponDFF5 = engineLoadDFF(":DayZ/models/weapons/dff/dragunov.dff", 0)
weaponTXD6 = engineLoadTXD(":DayZ/models/weapons/txd/bizon.txd")
weaponDFF6 = engineLoadDFF(":DayZ/models/weapons/dff/bizon.dff", 0)
weaponTXD7 = engineLoadTXD(":DayZ/models/weapons/txd/remington.txd")
weaponDFF7 = engineLoadDFF(":DayZ/models/weapons/dff/remington.dff", 0)
weaponTXD8 = engineLoadTXD(":DayZ/models/weapons/txd/revolver.txd")
weaponDFF8 = engineLoadDFF(":DayZ/models/weapons/dff/revolver.dff", 0)
weaponTXD9 = engineLoadTXD(":DayZ/models/weapons/txd/m1911.txd")
weaponDFF9 = engineLoadDFF(":DayZ/models/weapons/dff/m1911.dff", 0)
weaponTXD10 = engineLoadTXD(":DayZ/models/weapons/txd/sks.txd")
weaponDFF10 = engineLoadDFF(":DayZ/models/weapons/dff/sks.dff", 0)
weaponTXD11 = engineLoadTXD(":DayZ/models/weapons/txd/sa58v.txd")
weaponDFF11 = engineLoadDFF(":DayZ/models/weapons/dff/sa58v.dff", 0)


-- // Zombies // --
local skin = engineLoadTXD(":DayZ/models/zombies/txd/56.txd")
engineImportTXD(skin, 56)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/56.dff")
engineReplaceModel(skinDFF,56)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/67.txd")
engineImportTXD(skin, 67)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/67.dff")
engineReplaceModel(skinDFF,67)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/68.txd")
engineImportTXD(skin, 68)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/68.dff")
engineReplaceModel(skinDFF,68)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/69.txd")
engineImportTXD(skin, 69)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/69.dff")
engineReplaceModel(skinDFF,69)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/70.txd")
engineImportTXD(skin, 70)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/70.dff")
engineReplaceModel(skinDFF,70)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/84.txd")
engineImportTXD(skin, 84)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/92.txd")
engineImportTXD(skin, 92)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/92.dff")
engineReplaceModel(skinDFF,92)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/97.txd")
engineImportTXD(skin, 97)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/97.dff")
engineReplaceModel(skinDFF,97)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/105.txd")
engineImportTXD(skin, 105)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/105.dff")
engineReplaceModel(skinDFF,105)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/107.txd")
engineImportTXD(skin, 107)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/107.dff")
engineReplaceModel(skinDFF,107)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/108.txd")
engineImportTXD(skin, 108)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/108.dff")
engineReplaceModel(skinDFF,108)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/111.txd")
engineImportTXD(skin, 111)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/126.txd")
engineImportTXD(skin, 126)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/126.dff")
engineReplaceModel(skinDFF,126)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/127.txd")
engineImportTXD(skin, 127)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/127.dff")
engineReplaceModel(skinDFF,127)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/128.txd")
engineImportTXD(skin, 128)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/128.dff")
engineReplaceModel(skinDFF,128)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/152.txd")
engineImportTXD(skin, 152)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/152.dff")
engineReplaceModel(skinDFF,152)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/162.txd")
engineImportTXD(skin, 162)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/162.dff")
engineReplaceModel(skinDFF,162)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/167.txd")
engineImportTXD(skin, 167)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/167.dff")
engineReplaceModel(skinDFF,167)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/188.txd")
engineImportTXD(skin, 188)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/188.dff")
engineReplaceModel(skinDFF,188)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/192.txd")
engineImportTXD(skin, 192)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/195.txd")
engineImportTXD(skin, 195)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/195.dff")
engineReplaceModel(skinDFF,195)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/206.txd")
engineImportTXD(skin, 206)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/206.dff")
engineReplaceModel(skinDFF,206)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/209.txd")
engineImportTXD(skin, 209)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/209.dff")
engineReplaceModel(skinDFF,209)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/212.txd")
engineImportTXD(skin, 212)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/212.dff")
engineReplaceModel(skinDFF,212)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/229.txd")
engineImportTXD(skin, 229)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/229.dff")
engineReplaceModel(skinDFF,229)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/230.txd")
engineImportTXD(skin, 230)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/230.dff")
engineReplaceModel(skinDFF,230)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/258.txd")
engineImportTXD(skin, 258)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/258.dff")
engineReplaceModel(skinDFF,258)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/264.txd")
engineImportTXD(skin, 264)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/264.dff")
engineReplaceModel(skinDFF,264)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/274.txd")
engineImportTXD(skin, 274)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/277.txd")
engineImportTXD(skin, 277)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/277.dff")
engineReplaceModel(skinDFF,277)
local skin = engineLoadTXD(":DayZ/models/zombies/txd/280.txd")
engineImportTXD(skin, 280)
local skinDFF = engineLoadDFF(":DayZ/models/zombies/dff/280.dff")
engineReplaceModel(skinDFF,280)