--[[

	Name: Client-Side Language Tables
	Version: 0.1
	Copyright: DayZ Gamemode. All rights reserved to Developers
	Current Devs: Lawliet, CiBeR, Jboy
	
]]--

--[[ Defining Primary Language Tables ]]--
languageItemTable = {}
languageTextTable = {}
------------------------------------------

--[[ Defining Language Item Tables ]]--
--English
languageItemTable.en_EN = {
	["Weapons"] = {
		"M4",
		"AK-47",
		"Lee Enfield",
		"CZ 550",
		"MP5A5",
		"PDW",
		"SPAZ-12 Combat Shotgun",
		"Sawn-Off Shotgun",
		"Winchester 1866",
		"M9 SD",
		"M1911",
		"Blaze 95 Double Rifle",
		"Remington 870",
		"Sporter 22",
		"Revolver",
		"Bizon PP-19",
		"FN FAL",
		"G36C",
		"Sa58V CCO",
		"DMR",
		"SVD Dragunov",
		"SKS",
		"Crossbow",
		"Desert Eagle",
		"Binoculars",
		"Tear Gas",
		"Grenade",
		"Satchel",
		"Baseball Bat",
		"Shovel",
		"Golf Club",
		"Hunting Knife",
		"Hatchet"
	},
	
	["Ammo"] = {
		"5.56x45mm Cartridge",
		"5.45x39mm Cartridge",
		"9x18mm Cartridge",
		"9x19mm Cartridge",
		"9x19mm SD Cartridge",
		"9.3x62mm Cartridge",
		".45 ACP Cartridge",
		"Gauge 12 Pellet",
		"2Rnd. Slug",
		"1866 Slug",
		".303 British Cartridge",
		"Bolt",
		
	},
	
	["Food/Drinks"] = {
		"Baked Beans",
		"Pasta",
		"Sardines",
		"Frank & Beans",
		"Can (Corn)",
		"Can (Peas)",
		"Can (Pork)",
		"Can (Stew)",
		"Can (Ravioli)",
		"Can (Fruit)",
		"Can (Chowder)",
		"MRE",
		"Pistachios",
		"Trail Mix",
		"Water Bottle",
		"Soda Can (Pepsi)",
		"Soda Can (Cola)",
		"Soda Can (Mountain Dew)",
		"Can (Milk)",
		"Raw Meat",
		"Cooked Meat",
	},
	
	["Backpacks"] = {
		"Assault Pack (ACU)",
		"Czech Vest Pouch",
		"ALICE Pack",
		"Survival ACU",
		"British Assault Pack",
		"Backpack (Coyote)",
		"Czech Backpack",
	},
	
	["Toolbelt"] = {
		"Box of Matches",
		"IR Goggles",
		"NV Goggles",
		"GPS",
		"Map",
		"Toolbox",
		"Watch",
		"Radio Device",
		"Compass"
	},
	
	["Medical Items"] = {
		"Bandage",
		"Morphine",
		"Heat Pack",
		"Blood Bag",
		"Painkiller",
	},
	
	["Car Parts"] = {
		"Tire",
		"Engine",
		"Tank Parts",
	},
	
	["Clothes"] = {
		"Survivor Clothing",
		"Civilian Clothing",
		"Camouflage Clothing",
		"Ghillie Suit",
	},
	
	["Blueprints"] = {
		"M4 Blueprint",
		"CZ 550 Blueprint",
		"Winchester '66 Blueprint",
		"SPAZ-12 C. Shtgn. Blueprint",
		"Sawn-Off Shtgn. Blueprint",
		"AK-47 Blueprint",
		"Lee Enfield Blueprint",
		"Sporter 22 Blueprint",
		"Mosin 9130 Blueprint",
		"Crossbow Blueprint",
		"SKS Blueprint",
		"Blaze 95 D. R. Blueprint",
		"Remington 870 Blueprint",
		"FN FAL Blueprint",
		"G36C Blueprint",
		"Sa58V Blueprint",
		"SVD Blueprint",
		"DMR Blueprint",
		"M1911 Blueprint",
		"M9 SD Blueprint",
		"PDW Blueprint",
		"G17 Blueprint",
		"MP5A5 Blueprint",
		"Bizon PP-19 Blueprint",
		"Revolver Blueprint",
		"Desert Eagle Blueprint",
		"Hunting Knife Blueprint",
		"Hatchet Blueprint",
		"Baseball Bat Blueprint",
		"Shovel Blueprint",
		"Golf Club Blueprint",
		"Crowbar Blueprint",
		"Parachute Blueprint",
		"Grenade Blueprint",
		"Binoculars Blueprint",
		".45 ACP Cartridge Blueprint",
		"9x19mm SD Cartridge Blueprint",
		"9x19mm Cartridge Blueprint",
		"9x18mm Cartridge Blueprint",
		"5.45x39mm Cartridge Blueprint",
		"5.56x45mm Cartridge Blueprint",
		"1866 Slug Blueprint",
		"2Rnd. Slug Blueprint",
		"12 Gauge Pellet Blueprint",
		"9.3x62mm Cartridge Blueprint",
		".303 British Cartridge Blueprint",
		"Bolt Blueprint",
		"Wire Fence Blueprint",
		"Tent Blueprint",
		"Camouflage Clthng. Blueprint",
		"Survivor Clthng. Blueprint",
		"Civilian Clthng. Blueprint",
		"Ghillie Suit Blueprint",
		"Road Flare Blueprint",
		"Toolbox Blueprint",
		"Radio Device Blueprint",
		"IR Goggles Blueprint",
		"NV Goggles Blueprint",
	},
	
	["Blueprint Parts"] = {
		"Gun Barrel",
		"Short Gun Barrel",
		"Gun Stock",
		"Thread",
		"Cloth",
		"Gun Powder",
		"Mechanical Supplies",
		"Cables",
		"Nails",
		"Sheet",
		"Barbed Wire",
		"Duct Tape",
		"Glue",
		"Drugs",
		"Bandaid",
		"Vitamins",
		"Tissue",
		"Small Box",
		"String",
		"Needle",
		"Microchips",
		"Optics",
		"Sharp Metal",
		"Handle",
		"Wooden Stick",
		"Hand Saw",
		"Metal Plate",
		"Metallic Stick",
		"Small Casing",
	},
	
	["Other"] = {
		"Wood Pile",
		"Empty Gas Canister",
		"Full Gas Canister",
		"Road Flare",	
		"Wire Fence",
		"Tent"
	}
}
--Spanish
languageItemTable.es_ES = {

}
--Arabic
languageItemTable.ar_AR = {

}
--German
languageItemTable.de_DE = {

}
--Portuguese
languageItemTable.pt_PT = {

}
--French
languageItemTable.fr_FR = {

}
--Russian
languageItemTable.ru_RU = {

}
--Polish
languageItemTable.pl_PL = {

}
---------------------------------------

languageTextTable = {
-- English (US)
["en_US"] = {
	["Weapons"] = {
		["Primary Weapon"] = {
			{"M4",10, 'm4.png', 256, 128,"Penetrator", "Ammunition: 5.56x45mm Cartridge","M4"},
			{"CZ 550",10, 'cz550.png', 256,128,"Sniper", "Ammunition: 9.3x62mm Cartridge","CZ 550"},
			{"Winchester 1866",10, 'winchester.png', 256, 128 ,"Shotgun", "Ammunition: 1866 Slug","Winchester 1866"},
			{"SPAZ-12 Combat Shotgun",10, 'spaz.png', 256, 128 ,"Shotgun", "Ammunition: 12 Gauge Pellet","SPAZ-12 Combat Shotgun"},
			{"Sawn-Off Shotgun",10, 'sawn.png', 256, 128,"Shotgun", "Ammunition: 2Rnd. Slug","Sawn-Off Shotgun"},
			{"AK-47",10, 'ak47.png', 256, 128 ,"Assault Rifle", "Ammunition: 5.45x39mm Cartridge","AK-47"},
			{"Lee Enfield",10, 'enfield.png', 256, 128,"Repeating Rifle", "Ammunition: .303 British Cartridge","Lee Enfield"},
			{"Sporter 22",10,'enfield.png',256,128,"Repeating Rifle","Ammunition: .303 British Cartridge","Sporter 22"},
			{"Mosin 9130",10,'enfield.png',256,128,"Repeating Rifle","Ammunition: .303 British Cartridge","Mosin 9130"},
			{"Crossbow",10,'crossbow.png',128,128,"Crossbow","Ammunition: Bolt","Crossbow"},
			{"SKS",10,'enfield.png',256,128,"Repeating Rifle","Ammunition: .303 British Cartridge","SKS"},
			{"Blaze 95 Double Rifle",10,'spaz.png',256,128,"Shotgun","Ammunition: 2Rnd. Slug","Blaze 95 Double Rifle"},
			{"Remington 870",10,'remington.png',256,128,"Shotgun","Ammunition: 12 Gauge Pellet","Remington 870"},
			{"FN FAL",10,'fnfal.png',256,128,"Assault Rifle","Ammunition: 5.45x39mm Cartridge","FN FAL"},
			{"G36C",10,'g36c.png',256,128,"Assault Rifle","Ammunition: 5.45x39mm Cartridge","G36C"},
			{"Sa58V CCO",10,'sa58v.png',256,128,"Assault Rifle","Ammunition: 5.45x39mm Cartridge","Sa58V CCO"},
			{"SVD Dragunov",10,'svd.png',256,128,"Sniper","Ammunition: 9.3x62mm Cartridge","SVD Dragunov"},
			{"DMR",10,'dmr.png',256,128,"Sniper","Ammunition: 9.3x62mm Cartridge","DMR"},
		},

		["Secondary Weapon"] = {
			{"M1911",5, 'm1911.png', 128, 128,"Handgun", "Ammunition: .45 ACP Cartridge","M1911"},
			{"M9 SD",5, 'm9sd.png', 128, 128,"Handgun", "Ammunition: 9x19mm SD Cartridge","M9 SD"},
			{"PDW",5, 'pdw.png', 128, 128,"Sub-Machine Gun", "Ammunition: 9x19mm Cartridge","PDW"},
			{"G17",5,'g17.png',128,128,"Handgun","You shouldn't have this.","G17"},
			{"MP5A5",5, 'mp5a5.png', 128, 128,"Sub-Machine Gun", "Ammunition: 9x18mm Cartridge","MP5A5"},
			{"Desert Eagle",5, 'revolver.png',128,128,"Handgun","Ammunition: .45 ACP Cartridge","Desert Eagle"},
			{"Bizon PP-19",5,'bizon.png',128,128,"Sub-Machine Gun","Ammunition: 9x18mm Cartridge","Bizon PP-19"},
			{"Revolver",5,'revolver.png',128,128,"Handgun","Ammunition: .45 ACP Cartridge","Revolver"},
			{"Hunting Knife",5, 'knife.png',128,128,"Melee", "Ammunition: None","Hunting Knife"},
			{"Hatchet",5, 'hatchet.png',128,128,"Melee", "Ammunition: None","Hatchet"},
			{"Baseball Bat",5, 'bat.png', 128,128,"Melee", "Ammunition: None","Baseball Bat"},
			{"Shovel",5, 'shovel.png', 128, 128,"Melee", "Ammunition: None","Shovel"},
			{"Golf Club",5, 'golf.png', 128, 128,"Melee", "Ammunition: None","Golf Club"},
			{"Crowbar",5, 'crowbar.png',128,128,"Melee","Ammunition: None","Crowbar"},
		},

		["Specially Weapon"] = {
			{"Parachute",1, 'parachute.png', 128,128,"Item", "Equip to use.","Parachute"},
			{"Tear Gas",1, 'gas.png', 128, 128,"Item", "You shouldn't have this.","Tear Gas",},
			{"Grenade",5, 'grenade.png', 128, 128,"Item", "Extremely deadly and extremely noisy.","Grenade",},
			{"Binoculars",1, 'binoculars.png', 128, 128,"Item", "Click item to equip.","Binoculars"}
		},

	},

	["Ammo"] = {
		{".45 ACP Cartridge",0.085, '45acp.png',128,128,"Ammunition", "For:\nM1911\nDesert Eagle\nRevolver",".45 ACP Cartridge"},
		{"9x19mm SD Cartridge",0.085, '9x19sd.png',128,128,"Ammunition", "For:\nM9 SD","9x19mm SD Cartridge"},
		{"9x19mm Cartridge",0.025, '9x19.png',128,128,"Ammunition", "For:\nPDW","9x19mm Cartridge"},
		{"9x18mm Cartridge",0.025, '9x18.png',128,128,"Ammunition", "For:\nMP5A5\nBizon PP-19","9x18mm Cartridge"},
		{"5.45x39mm Cartridge",0.035, 'ak.png',128,128,"Ammunition", "For:\nAK-47\nG36C\nFN FAL","5.45x39mm Cartridge"},
		{"5.56x45mm Cartridge",0.035, 'm4.png',128,128,"Ammunition", "For:\nM4","5.56x45mm Cartridge"},
		{"1866 Slug",0.067, 'shotgun.png',128,128,"Ammunition", "For:\nWinchester 1866","1866 Slug"},
		{"2Rnd. Slug",0.067, 'shotgun.png',128,128,"Ammunition", "For:\nSawn-Off Shotgun\nBlaze 95 Double Rifle","2Rnd. Slug"},
		{"12 Gauge Pellet",0.067, 'shotgun.png',128,128,"Ammunition", "For:\nSPAZ-12 C. Shotgun\nRemington 870","12 Gauge Pellet"},
		{"9.3x62mm Cartridge",0.1, 'sniper.png',128,128,"Ammunition", "For:\nCZ 550\nDMR\nSVD Dragunov","9.3x62mm Cartridge"},
		{".303 British Cartridge",0.1, 'british.png',128,128,"Ammunition", "For:\nLee Enfield\nSporter 22\nMosin 9130\nSKS",".303 British Cartridge"},
		{"Bolt",0.1,'arrow.png',128,128,"Ammunition","For:\nCrossbow","Bolt"},
	},

	["Food"] = {
		{"Baked Beans",1,'bakedbeans.png',128,128,"Food", "Canned Baked Beans used for sustainment.\nLasts well over five years if stored \ncorrectly.","Baked Beans",},
		{"Pasta",1,'pasta.png',128,128,"Food", "Canned Pasta used for sustainment.\nLasts well over five years if stored \ncorrectly.","Pasta"},
		{"Sardines",1,'sardines.png',128,128,"Food", "Canned Sardines used for sustainment.\nLasts well over five years if stored \ncorrectly.","Sardines"},
		{"Frank & Beans",1,'frankbeans.png',128,128,"Food","Canned Frank & Beans used for sustainment.\nLasts well over five years if stored \ncorrectly.","Frank & Beans"},
		{"Can (Corn)",1,'corn.png',128,128,"Food", "A clean, unopened tin can of corn.","Can (Corn)"},
		{"Can (Peas)",1,'peas.png',128,128,"Food", "A clean, unopened tin can of peas.","Can (Peas)"},
		{"Can (Pork)",1,'pork.png',128,128,"Food", "A clean, unopened tin can of pork.", "Can (Pork)"},
		{"Can (Stew)",1,'stew.png',128,128,"Food", "A clean, unopened tin can of beef stew.", "Can (Stew)"},
		{"Can (Ravioli)",1,'ravioli.png',128,128,"Food", "A clean, unopened tin can of ravioli.", "Can (Ravioli)"},
		{"Can (Fruit)",1,'fruit.png',128,128,"Food", "A clean, unopened tin can of mixed fruits.", "Can (Fruit)"},
		{"Can (Chowder)",1,'chowder.png',128,128,"Food", "A clean, unopened tin can of clam chowder.", "Can (Chowder)"},
		{"MRE",1,'mre.png', 128, 128,"Food", "Meal Ready-to-Eat.","MRE"},
		{"Pistachios",1,'pistachios.png', 128, 128,"Food", "A pack of pistachios, roasted and salted.","Pistachios"},
		{"Trail Mix",1,'trailmix.png', 128, 128,"Food", "Contains twelve different fruits and nuts.","Fruit Mix"},
		{"Cooked Meat",1, 'cookedmeat.png',128,128,"Food", "Meat that has been cooked over a fire.","Cooked Meat"},
		{"Water Bottle",1, 'bottle.png', 128, 128,"Drink", "A bottle of water that has been\nfiltered and can be consumed.","Water Bottle"},
		{"Soda Can (Pepsi)",1,'pepsi.png', 128, 128,"Drink", "An aluminium can containing a tasty\ncarbonated beverage full of sugar,\nartificial flavors, and preservatives.","Soda Can (Pepsi)"},
		{"Soda Can (Cola)",1,'cola.png', 128, 128,"Drink", "An aluminium can containing a tasty\ncarbonated beverage full of sugar,\nartificial flavors, and preservatives.","Soda Can (Cola)"},
		{"Soda Can (Mountain Dew)",1,'dew.png', 128, 128,"Drink", "An aluminium can containing a tasty\ncarbonated beverage full of sugar,\nartificial flavors, and preservatives.", "Soda Can (Mountain Dew)"},
		{"Can (Milk)",1,'milkcan.png',128,128,"Drink", "An aluminium can containing a tasty\ncarbonated beverage full of sugar,\nartificial flavors, and preservatives.", "Can (Milk)"},
	},

	["Items"] = {
		{"Wood Pile",2, 'wood.png',128,128,"Item", "A small pile of freshly chopped\nwood that can be used for making\na fireplace and various other things.","Wood Pile"},
		{"Bandage",1, 'bandage.png', 128, 128, "Item", "Joint Services standard first aid dressing.\nUsed to stop bleeding of wounds.","Bandage","Bandage yourself"},
		{"Road Flare",1, 'roadflare.png', 128, 128, "Item", "Hand operated flare commonly found\n in roadside emergency kits. Will burn\n for approximately five minutes.","Road Flare","Place"},
		{"Empty Gas Canister",3, 'canister.png', 128, 128,"Item", "20L Jerry Can that can be used for\nrefuelling vehicles and powering generators.\nIt's empty.","Empty Gas Canister"},
		{"Full Gas Canister",3, 'canister.png', 128, 128,"Item", "20L Jerry Can that can be used for\nrefuelling vehicles and powering generators.","Full Gas Canister"},
		{"Medic Kit",2, 'chest.png', 128, 128, "Item", "<You shouldn't have this.>","Medic Kit","Use"},
		{"Heat Pack",1, 'heatpack.png', 128, 128, "Item", "A heating pad that heats when you\nstart the crystallisation process.\nUsed to provide quick warmth to your body.","Heat Pack","Use"},
		{"Painkiller",1, 'painkillers.png', 128, 128, "Item", "A moderate painkiller suitable\nfor regular use of relief of pain\nand inflammation caused by moderate \nwounds.","Painkillers","Use"},
		{"Morphine",1, 'morphine.png',128,128,"Item", "Used for intramuscular injection to manage\nsevere pain such as those from fractures.","Morphine","Use"},
		{"Blood Bag",1, 'bloodbag.png', 128, 85, "Item", "Bag of blood used for administering\na blood transfusion.","Blood Bag","Use"},
		{"Wire Fence", 1, 'wirefence.png', 128, 128, "Item", "Razor wire in large coils which\ncan be expanded like a concertina with\nsteel pickets to form military wire obstacles.","Wire Fence","Build a wire fence"}, 
		{"Raw Meat", 1, 'rawmeat.png', 128, 128,"Item", "Raw meat gutted from an animal.","Raw Meat"}, 
		{"Tire", 2, 'wheel.png', 128, 128,"Item", "An old car wheel that could be\nused to repair a vehicle with a broken one.","Tire"}, 
		{"Engine", 5, 'engine.png', 128,128,"Item", "Engine components with oil and lubricant.\nEverything you would need to repair an engine.","Engine"}, 
		{"Tank Parts", 3, 'engine_part.png', 128,128,"Item", "An old fuel tank that could be used\nto repair a vehicle with a broken one.","Tank Parts"},
		{"Main Rotary Parts", 6, 'rotary.png', 128, 128,"Item", "Parts for a helicopter.","Main Rotary Parts"}, 
		{"Scrap Metal", 3, 'parts.png', 128,128,"Item", "Old metal, can be used to\n to repair vehicles.","Scrap Metal"},
		{"Windscreen Glass", 2, 'glass.png', 128, 128,"Item", "A windscreen glass for a vehicle.","Windscreen Glass"}, 	
		{"Tent", 3, 'tent.png', 128, 128, "Item", "A camping tent that can be pitched,\nallowing you extended storage\nsafe from others.","Tent","Pitch a tent"}, 
		{"Camouflage Clothing",1,'clothes.png',128,128,"Item","A mixture of camouflage trousers\n with a brown t-shirt and no hat.\nCan be unpacked and worn.","Camouflage Clothing","Put clothes on"},
		{"Civilian Clothing",1,'clothes.png',128,128,"Item","A normal mixture of civilian clothing\n with a light-weight vest and hat.\nCan be unpacked and worn.","Civilian Clothing","Put clothes on"},
		{"Civilian Clothing (Female)",1,'clothes.png',128,128,"Item","A normal mixture of female civilian clothing\n with a light-weight vest and hat.\nCan be unpacked and worn.","Civilian Clothing (F)","Put clothes on"},
		{"Survivor Clothing (Female)",1,'clothes.png',128,128,"Item","Use to 'adorn' yourself\nwith new clothes.","Survivor Clothing (F)","Put clothes on"},
		{"Survivor Clothing",1,'clothes.png',128,128,"Item","Use to 'adorn' yourself\nwith new clothes.","Survivor Clothing","Put clothes on"},
		{"Ghillie Suit",1,'clothes.png',128,128,"Item","A type of camouflage clothing\ndesigned to resemble heavy foliage.\nCan be unpacked and worn.","Ghillie Suit","Put clothes on"},
		{"Empty Water Bottle", 1, 'emptybottle.png', 128, 128,"Item", "A bottle of water that has been\nfiltered and can be consumed.\nIt's empty, though.","Empty Water Bottle", "Fill bottle up"}, 
		{"Empty Soda Can", 1,'emptysoda.png', 128, 128,"Item", "A aluminium can that once contained\na tasty carbonated beverage,\nand now contains nothing.","Empty Soda Cans"}, 
		{"Assault Pack (ACU)",1,'acu.png',170,170,"Item", "Gives you +12 slots.","Assault Pack (ACU)"},
		{"Czech Vest Pouch",1,'czechpouch.png',170,170,"Item", "Gives you +13 slots.","Czech Vest Pouch"},
		{"ALICE Pack",1,'alice.png',170,170,"Item", "Gives you +16 slots.","ALICE Pack"},
		{"Survival ACU",1,'survival.png',170,170,"Item", "Gives you +17 slots.","Survival ACU"},
		{"British Assault Pack",1,'britishpack.png',170,170,"Item", "Gives you +18 slots.","British Assault Pack"},
		{"Backpack (Coyote)",1,'coyote.png',170,170,"Item", "Gives +24 slots.","Backpack (Coyote)"},
		{"Czech Backpack",1,'czech.png',170,170,"Item", "Gives +30 slots.","Czech Backpack"},
		{"San Fierro Carrier Keycard",1,'keycard.png',170,170,"Item","Allows you to open the door\nin the San Fierro Carrier.\nIs consumed after use.","SF Carrier Keycard","Activate"},
		{"Area 69 Keycard",1,'keycard.png',170,170,"Item","Allows you to open the door\nin Area 69.\nIs consumed after use.","Area 69 Keycard","Activate"},
		{"M4 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nNails(x2)","M4 Blueprint","Craft"},
		{"CZ 550 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nOptics(x1)","CZ 550 Blueprint","Craft"},
		{"Winchester '66 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x2)\nGun Stock(x1)\nDuct Tape(x4)","Winchester '66 Blueprint","Craft"},
		{"SPAZ-12 C. Shtgn. Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x2)\nGun Stock(x1)\nDuct Tape(x4)","SPAZ-12 C. Shtgn. Blueprint","Craft"},
		{"Sawn-Off Shtgn. Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x2)\nGun Stock(x2)\nDuct Tape(x2)","Sawn-Off Shtgn. Blueprint","Craft"},
		{"AK-47 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nNails(x2)","AK-47 Blueprint","Craft"},
		{"Lee Enfield Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nDuct Tape(x2)","Lee Enfield","Craft"},
		{"Sporter 22 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nDuct Tape(x2)","Sporter 22 Blueprint","Craft"},
		{"Mosin 9130 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nDuct Tape(x2)","Mosin 9130 Blueprint","Craft"},
		{"Crossbow Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x2)\nHandle(x1)\nWooden Stick(x2)","Crossbow Blueprint","Craft"},
		{"SKS Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nDuct Tape(x2)","SKS Blueprint","Craft"},
		{"Blaze 95 D. R. Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x2)\nGun Stock(x1)\nDuct Tape(x4)","Blaze 95. D. R. Blueprint","Craft"},
		{"Remington 870 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x2)\nGun Stock(x1)\nDuct Tape(x4)","Remington 870","Craft"},
		{"FN FAL Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nNails(x2)","FN FAL Blueprint","Craft"},
		{"G36C Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nNails(x2)","G36C Blueprint","Craft"},
		{"Sa58V CCO Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nNails(x2)","Sa58V CCO Blueprint","Craft"},
		{"SVD Dragunov Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nOptics(x1)","SVD Dragunov Blueprint","Craft"},
		{"DMR Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGun Barrel(x1)\nGun Stock(x1)\nOptics(x1)","DMR Blueprint","Craft"},
		{"M1911 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\nNails(x2)","M1911 Blueprint","Craft"},
		{"M9 SD Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\Metallic Stick(x1)","M9 SD Blueprint","Craft"},
		{"PDW Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\nNails(x2)","PDW Blueprint","Craft"},
		{"G17 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\nGlue(x2)","G17 Blueprint","Craft"},
		{"MP5A5 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\nDuct Tape(x2)","MP5A5 Blueprint","Craft"},
		{"Bizon PP-19 Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\nDuct Tape(x2)","Bizon PP-19 Blueprint","Craft"},
		{"Revolver Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\nNails(x3)","Revolver Blueprint","Craft"},
		{"Desert Eagle Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nShort Gun Barrel(x1)\nGun Stock(x1)\nNails(x3)","Desert Eagle Blueprint","Craft"},
		{"Hunting Knife Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nHandle(x1)\nSharp Metal(x1)\nGlue(x1)","Hunting Knife Blueprint","Craft"},
		{"Hatchet Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nHandle(x1)\nMetal Plate(x1)\nBarbed Wire(x1)","Hatchet Blueprint","Craft"},
		{"Baseball Bat Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:Wooden Stick\n(x1)\nNails(x1)\nGlue(x1)","Baseball Bat Blueprint","Craft"},
		{"Shovel Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nWooden Stick(x1)\nMetal Plate(x1)\nNails(x1)","Shovel Blueprint","Craft"},
		{"Golf Club Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nMetallic Stick(x1)\nMetal Plate(x1)\nBarbed Wire(x1)","Golf Club Blueprint","Craft"},
		{"Machete Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nHandle(x1)\nSharp Metal(x2)\nGlue(x2)","Machete Blueprint","Craft"},
		{"Crowbar Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nMetallic Stick(x1)\nHand Saw(x1)\nDuct Tape(x1)","Crowbar Blueprint","Craft"},
		{"Parachute Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nString(x4)\nCloth(x2)\nSheet(x2)","Parachute Blueprint","Craft"},
		{"Tear Gas Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nGlue(x2)\nSmall Casing(x1)\nString(x1)","Tear Gas Blueprint","Craft"},
		{"Grenade Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x4)\nCables(x1)","Grenade Blueprint","Craft"},
		{"Binoculars Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nOptics(x2)\nSmall Box(x1)\nGlue(x1)","Binoculars Blueprint","Craft"},
		{".45 ACP Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)",".45 ACP Cartridge Blueprint","Craft"},
		{"9x19mm SD Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","9x19mm SD Cartridge Blueprint","Craft"},
		{"9x19mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","9x19mm Cartridge Blueprint","Craft"},
		{"9x18mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","9x18mm Cartridge Blueprint","Craft"},
		{"5.45x39mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","5.45x39mm Cartridge Blueprint","Craft"},
		{"5.56x45mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","5.56x45mm Cartridge Blueprint","Craft"},
		{"1866 Slug Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","1866 Slug Blueprint","Craft"},
		{"2Rnd. Slug Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","2Rnd. Slug Blueprint","Craft"},
		{"12 Gauge Pellet Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","12 Gauge Pellet Blueprint","Craft"},
		{"9.3x62mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)","9.3x62mm Cartridge Blueprint","Craft"},
		{".303 British Cartridge Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Casing(x1)\nGun Powder(x2)\nGlue(x1)",".303 British Cartridge Blueprint","Craft"},
		{"Bolt Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nWooden Stick(x2)\nSharp Metal(x2)\nHand Saw(x1)","Bolt Blueprint","Craft"},
		{"Medic Kit Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nDrugs(x2)\nVitamins(x2)\nBandaid(x1)","Medic Kit Blueprint","Craft"},
		{"Wire Fence Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nBarbed Wire(x1)\nWooden Stick(x2)\nDuct Tape(x1)","Wire Fence Blueprint","Craft"},
		{"Tent Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nString(x1)\nSheet(x2)\nWooden Stick(x1)","Tent Blueprint","Craft"},
		{"Camouflage Clthng. Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nThread(x3)\nCloth(x1)\nNeedle(x1)","Camouflage Clthng. Blueprint","Craft"},
		{"Survivor Clthng. Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nThread(x3)\nCloth(x1)\nNeedle(x1)","Survivor Clthng. Blueprint","Craft"},
		{"Civilian Clthng. Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nThread(x3)\nCloth(x1)\nNeedle(x1)","Civilian Clthng. Blueprint","Craft"},
		{"Ghillie Suit Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nThread(x3)\nCloth(x3)\nNeedle(x2)","Ghillie Suit Blueprint","Craft"},
		{"Road Flare Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nSmall Box(x1)\nGun Powder(x1)\nTissue(x1)","Road Flare Blueprint","Craft"},
		{"Toolbox Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nMechanical Supplies(x1)\nSmall Box(x1)\nHand Saw(x1)","Toolbox Blueprint","Craft"},
		{"Radio Device Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nMicrochips(x2)\nSmall Box(x1)\nMechanical Supplies(x1)","Radio Device Blueprint","Craft"},
		{"IR Goggles Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nOptics(x3)\nMicrochips(x4)\nGlue(x1)","IR Goggles Blueprint","Craft"},
		{"NV Goggles Blueprint",1,'blueprint.png',128,128,"Blueprint","Components:\nOptics(x3)\nMicrochips(x4)\nGlue(x1)","NV Goggles Blueprint","Craft"},
		{"Gun Barrel",1,'parts.png',128,128,"Used in:","Universal component for primary weapons.","Gun Barrel"},
		{"Short Gun Barrel",1,'parts.png',128,128,"Used in:","Universal component for secondary weapons.","Short Gun Barrel"},
		{"Gun Stock",1,'parts.png',128,128,"Used in:","Universal component for all guns.","Gun Stock"},
		{"Thread",1,'parts.png',128,128,"Used in:","A thread. What did you expect?","Thread"},
		{"Cloth",1,'parts.png',128,128,"Component","Can be used to craft various clothings.","Cloth"},
		{"Gun Powder",1,'parts.png',128,128,"Component","Universal component for ammunition.","Gun Powder"},
		{"Mechanical Supplies",1,'parts.png',128,128,"Component","Universal component for electronics.","Mechanical Supplies"},
		{"Cables",1,'parts.png',128,128,"Component","Universal component for electronics.","Cables"},
		{"Nails",1,'parts.png',128,128,"Component","Universal component used in various blueprints.","Nails"},
		{"Sheet",1,'parts.png',128,128,"Component","A sheet. What else did you expect?","Sheet"},
		{"Barbed Wire",1,'parts.png',128,128,"Component","Used for tactical consumables like the Wire Fence.","Barbed Wire"},
		{"Duct Tape",1,'parts.png',128,128,"Component","Universal component used for electronics.","Duct Tape"},
		{"Glue",1,'parts.png',128,128,"Component","Universal component used for electronics.","Glue"},
		{"Drugs",1,'parts.png',128,128,"Component","Can be used for medical consumables.","Drugs"},
		{"Bandaid",1,'parts.png',128,128,"Component","Can be used for medical consumables.","Bandaid"},
		{"Vitamins",1,'parts.png',128,128,"Component","Can be used for medical consumables.","Vitamins"},
		{"Tissue",1,'parts.png',128,128,"Component","Can be used for medical consumables.","Tissue"},
		{"Small Box",1,'parts.png',128,128,"Component","A small box.","Small Box"},
		{"String",1,'parts.png',128,128,"Component","A rather long string.","String"},
		{"Needle",1,'parts.png',128,128,"Component","A sharp instrument for sowing.","Needle"},
		{"Microchips",1,'parts.png',128,128,"Component","Can be used for electric consumables.","Microchips"},
		{"Optics",1,'parts.png',128,128,"Component","Can be used for items like the binoculars.","Optics"},
		{"Sharp Metal",1,'parts.png',128,128,"Component","Piece of sharp metal.\nNot sharp enough to see usage\nas a weapon, though.","Sharp Metal"},
		{"Handle",1,'parts.png',128,128,"Component","A fine piece of handle.","Handle"},
		{"Wooden Stick",1,'parts.png',128,128,"Component","Some random stick found somewhere.","Wooden Stick"},
		{"Hand Saw",1,'parts.png',128,128,"Component","Commonly used on building lots.","Hand Saw"},
		{"Metal Plate",1,'parts.png',128,128,"Component","A rather heavy metal plate.","Metal Plate"},
		{"Metallic Stick",1,'parts.png',128,128,"Component","A metallic stick. Too short\nto be used as a weapon.","Metallic Stick"},
		{"Small Casing",1,'parts.png',128,128,"Component","A small casing to store things.","Small Casing"},
	},

	["Toolbelt"] = {
		{"NV Goggles", 1,'nvgoggles.png',128,128,"Item", "Press 'N' to activate.","NV Goggles"}, 
		{"IR Goggles", 1,'nvgoggles.png',128,128,"Item", "Press 'I' to activate.","IR Goggles"}, 
		{"Map", 1,'map.png',128,128,"Item", "Press 'F11' to activate.","Map"}, 
		{"Box of Matches", 1, 'matchbox.png',100,100,"Item", "Use in combination with 'Wood Pile'\nto create a fire.","Box of Matches", "Make a Fire"}, 
		{"Watch", 1,'watch.png',128,128,"Item", "Passive item, will be\nactivated when picking up.","Watch"}, 
		{"GPS", 1,'gps.png',128,128,"Item", "Passive item, will be\nactivated when picking up.","GPS"}, 
		{"Toolbox", 1,'toolbox.png',128,128,"Item", "Used to repair cars\nof all kinds.","Toolbox"}, 
		{"Radio Device", 1,'radio.png',128,128,"Item", "Press 'Z' to activate.","Radio Device"},
		{"Compass",1,'compass.png',128,128,"Item","Passive item, will be\nactivated when picking up.","Compass"},
	},

	},

-- German (Deutsch)
["de"] = {
	["Weapons"] = {
		["Primary Weapon"] = {
			{"M4",10, 'm4.png', 256, 128,"Sturmgewehr", "Munition: 5.56x45mm Patronen","M4"},
			{"CZ 550",10, 'cz550.png', 256,128,"Scharfschützengewehr", "Munition: 9.3x62mm Patronen","CZ 550"},
			{"Winchester 1866",10, 'winchester.png', 256, 128 ,"Schrotflinte", "Munition: 1866 Gewehrkugeln","Winchester 1866"},
			{"SPAZ-12 Combat Shotgun",10, 'spaz.png', 256, 128 ,"Schrotflinte", "Munition: Kaliber 12 Schrotkugeln","SPAZ-12 Kampfschrotflinte"},
			{"Sawn-Off Shotgun",10, 'sawn.png', 256, 128,"Schrotflinte", "Munition: 2 Gewehrkugeln","Abgesägte Schrotflinte"},
			{"AK-47",10, 'ak47.png', 256, 128 ,"Sturmgewehr", "Munition: 5.45x39mm Patronen","AK-47"},
			{"Lee Enfield",10, 'enfield.png', 256, 128,"Repetiergewehr", "Munition: .303 British Patronen","Lee Enfield"},
			{"Sporter 22",10,'enfield.png',256,128,"Repetiergewehr","Munition: .303 British Patronen","Sporter 22"},
			{"Mosin 9130",10,'enfield.png',256,128,"Repetiergewehr","Munition: .303 British Patronen","Mosin 9130"},
			{"Crossbow",10,'crossbow.png',128,128,"Armbrust","Munition: Bolzen","Armbrust"},
			{"SKS",10,'enfield.png',256,128,"Repetiergewehr","Munition: .303 British Patronen","SKS"},
			{"Blaze 95 Double Rifle",10,'spaz.png',256,128,"Schrotflinte","Munition: 2 Gewehrkugeln","Blaze 95 Doppelgewehr"},
			{"Remington 870",10,'remington.png',256,128,"Schrotflinte","Munition: Kaliber 12 Schrotkugeln","Remington 870"},
			{"FN FAL",10,'fnfal.png',256,128,"Sturmgewehr","Munition: 5.45x39mm Patronen","FN FAL"},
			{"G36C",10,'g36c.png',256,128,"Sturmgewehr","Munition: 5.45x39mm Patronen","G36C"},
			{"Sa58V CCO",10,'sa58v.png',256,128,"Sturmgewehr","Munition: 5.45x39mm Patronen","Sa58V CCO"},
			{"SVD Dragunov",10,'svd.png',256,128,"Scharfschützengewehr","Munition: 9.3x62mm Patronen","SVD Dragunov"},
			{"DMR",10,'dmr.png',256,128,"Scharfschützengewehr","Munition: 9.3x62mm Patronen","DMR"},
		},

		["Secondary Weapon"] = {
			{"M1911",5, 'm1911.png', 128, 128,"Handfeuerwaffe", "Munition: .45 ACP Patronen","M1911"},
			{"M9 SD",5, 'm9sd.png', 128, 128,"Handfeuerwaffe", "Munition: 9x19mm SD Patronen","M9 SD"},
			{"PDW",5, 'pdw.png', 128, 128,"Maschinenpistole", "Munition: 9x19mm Patronen","PDW"},
			{"G17",5,'g17.png',128,128,"Handfeuerwaffe","Munition: 9x19mm Patronen","G17"},
			{"MP5A5",5, 'mp5a5.png', 128, 128,"Maschinenpistole", "Munition: 9x18mm Patronen","MP5A5"},
			{"Desert Eagle",5, 'revolver.png',128,128,"Handfeuerwaffe","Munition: .45 ACP Patronen","Desert Eagle"},
			{"Bizon PP-19",5,'bizon.png',128,128,"Maschinenpistole","Munition: 9x18mm Patronen","Bizon PP-19"},
			{"Revolver",5,'revolver.png',128,128,"Handfeuerwaffe","Munition: .45 ACP Patronen","Revolver"},
			{"Hunting Knife",5, 'knife.png',128,128,"Nahkampfwaffe", "Munition: Keine","Jagdmesser"},
			{"Hatchet",5, 'hatchet.png',128,128,"Nahkampfwaffe", "Munition: Keine","Beil"},
			{"Baseball Bat",5, 'bat.png', 128,128,"Nahkampfwaffe", "Munition: Keine","Baseballschläger"},
			{"Shovel",5, 'shovel.png', 128, 128,"Nahkampfwaffe", "Munition: Keine","Schaufel"},
			{"Golf Club",5, 'golf.png', 128, 128,"Nahkampfwaffe", "Munition: Keine","Golfschläger"},
			{"Crowbar",5, 'crowbar.png',128,128,"Nahkampfwaffe","Munition: Keine","Brechstange"},
		},

		["Specially Weapon"] = {
			{"Parachute",1, 'parachute.png', 128,128,"Item", "Ausrüsten um diesen Gegenstand\nzu benutzen.","Fallschirm"},
			{"Tear Gas",1, 'gas.png', 128, 128,"Item", "Das solltest du nicht haben.","Tränengas",},
			{"Grenade",5, 'grenade.png', 128, 128,"Item", "Extrem tödlich und extrem laut.","Granate",},
			{"Binoculars",1, 'binoculars.png', 128, 128,"Item", "Zum Ausrüsten auf Icon klicken.","Fernglas"}
		},

	},

	["Ammo"] = {
		{".45 ACP Cartridge",0.085, '45acp.png',128,128,"Munition", "Für:\nM1911\nDesert Eagle\nRevolver",".45 ACP Patronen"},
		{"9x19mm SD Cartridge",0.085, '9x19sd.png',128,128,"Munition", "Für:\nM9 SD","9x19mm SD Patronen"},
		{"9x19mm Cartridge",0.025, '9x19.png',128,128,"Munition", "Für:\nPDW","9x19mm Patronen"},
		{"9x18mm Cartridge",0.025, '9x18.png',128,128,"Munition", "Für:\nMP5A5\nBizon PP-19","9x18mm Patronen"},
		{"5.45x39mm Cartridge",0.035, 'ak.png',128,128,"Munition", "Für:\nAK-47\nG36C\nFN FAL","5.45x39mm Patronen"},
		{"5.56x45mm Cartridge",0.035, 'm4.png',128,128,"Munition", "Für:\nM4","5.56x45mm Patronen"},
		{"1866 Slug",0.067, 'shotgun.png',128,128,"Munition", "Für:\nWinchester 1866","1866 Gewehrkugeln"},
		{"2Rnd. Slug",0.067, 'shotgun.png',128,128,"Munition", "Für:\nSawn-Off Shotgun\nBlaze 95 Double Rifle","2 Gewehrkugeln"},
		{"12 Gauge Pellet",0.067, 'shotgun.png',128,128,"Munition", "Für:\nSPAZ-12 C. Shotgun\nRemington 870","Kaliber 12 Schrotkugeln"},
		{"9.3x62mm Cartridge",0.1, 'sniper.png',128,128,"Munition", "Für:\nCZ 550\nDMR\nSVD Dragunov","9.3x62mm Patronen"},
		{".303 British Cartridge",0.1, 'british.png',128,128,"Munition", "Für:\nLee Enfield\nSporter 22\nMosin 9130\nSKS",".303 British Patronen"},
		{"Bolt",0.1,'arrow.png',128,128,"Munition","Für:\nCrossbow","Bolzen"},
	},

	["Food"] = {
		{"Baked Beans",1,'bakedbeans.png',128,128,"Nahrung", "Gebackene Bohnen, perfekt zum Überleben.\nKönnen unter den richtigen\nLagerbedingungen über 5 Jahre halten.","Gebackene Bohnen",},
		{"Pasta",1,'pasta.png',128,128,"Nahrung", "Pasta, perfekt zum Überleben.\nKönnen unter den richtigen\nLagerbedingungen über 5 Jahre halten.","Pasta"},
		{"Sardines",1,'sardines.png',128,128,"Nahrung", "Sardinen, perfekt zum Überleben.\nKönnen unter den richtigen\nLagerbedingungen über 5 Jahre halten.","Sardinen"},
		{"Frank & Beans",1,'frankbeans.png',128,128,"Nahrung","Würstchen & Bohnen, perfekt zum Überleben.\nKönnen unter den richtigen\nLagerbedingungen über 5 Jahre halten.","Würstchen & Bohnen"},
		{"Can (Corn)",1,'corn.png',128,128,"Nahrung", "Eine saubere, ungeöffnete Dose mit Mais.","Dose (Mais)"},
		{"Can (Peas)",1,'peas.png',128,128,"Nahrung", "Eine saubere, ungeöffnete Dose mit Erbsen.","Dose (Erbsen)"},
		{"Can (Pork)",1,'pork.png',128,128,"Nahrung", "Eine saubere, ungeöffnete Dose mit\nSchweinefleisch.", "Dose (Schweinefleisch)"},
		{"Can (Stew)",1,'stew.png',128,128,"Nahrung", "Eine saubere, ungeöffnete Dose mit Eintopf.", "Dose (Eintopf)"},
		{"Can (Ravioli)",1,'ravioli.png',128,128,"Nahrung", "Eine saubere, ungeöffnete Dose mit Ravioli.", "Dose (Ravioli)"},
		{"Can (Fruit)",1,'fruit.png',128,128,"Nahrung", "Eine saubere, ungeöffnete Dose mit Früchten.", "Dose (Früchte)"},
		{"Can (Chowder)",1,'chowder.png',128,128,"Nahrung", "Eine saubere, ungeöffnete Dose Suppe.", "Dose (Suppe)"},
		{"MRE",1,'mre.png', 128, 128,"Nahrung", "Meal Ready-to-Eat.\nEnthält alles, was man braucht.","MRE"},
		{"Pistachios",1,'pistachios.png', 128, 128,"Nahrung", "Eine Packung gesalzener\nundgerösteter Pistazien.","Pistazien"},
		{"Trail Mix",1,'trailmix.png', 128, 128,"Nahrung", "Enthält 12 verschiedene Sorten\nFrüchte und Nüsse.","Früchtemix"},
		{"Cooked Meat",1, 'cookedmeat.png',128,128,"Nahrung", "Fleisch, das über einem\nFeuer gebraten wurde.","Gebratenes Fleisch"},
		{"Water Bottle",1, 'bottle.png', 128, 128,"Drink", "Eine Flasche gefiltertes Wasser.\nKann gefahrlos getrunken werden.","Wasserflasche"},
		{"Soda Can (Pepsi)",1,'pepsi.png', 128, 128,"Drink", "Ein Getränk bestehend aus Kohlensäure,\nZucker, künstlichen Geschmacks-\nund Konservierungstoffen.","Getränkedose (Pepsi)"},
		{"Soda Can (Cola)",1,'cola.png', 128, 128,"Drink", "Ein Getränk bestehend aus Kohlensäure,\nZucker, künstlichen Geschmacks-\nund Konservierungstoffen.","Getränkedose (Cola)"},
		{"Soda Can (Mountain Dew)",1,'dew.png', 128, 128,"Drink", "Ein Getränk bestehend aus Kohlensäure,\nZucker, künstlichen Geschmacks-\nund Konservierungstoffen.", "Getränkedose (Mountain Dew)"},
		{"Can (Milk)",1,'milkcan.png',128,128,"Drink", "Eine Dose mit Milch.\n Das Haltbarkeitsdatum ist bald erreicht.", "Dose (Milch)"},
	},

	["Items"] = {
		{"Wood Pile",2, 'wood.png',128,128,"Item", "Ein Stapel Holz, kann für ein\nFeuer verwendet werden.","Holzstapel"},
		{"Bandage",1, 'bandage.png', 128, 128, "Item", "Joint Services Standard Erste Hilfe Verbandszeug.\nWird zum Stoppen von Blutungen verwendet.","Wundverband","Bandage yourself"},
		{"Road Flare",1, 'roadflare.png', 128, 128, "Item", "So etwas findet man häufig in Notfallkästen.\nBrennt für etwa 5 Minuten.","Leuchtfeuer","Place"},
		{"Empty Gas Canister",3, 'canister.png', 128, 128,"Item", "20L Kanister zum Auffüllen des Tanks\nbei Fahrzeugen. Ist leer.","Leerer Benzinkanister"},
		{"Full Gas Canister",3, 'canister.png', 128, 128,"Item", "20L Kanister zum Auffüllen des Tanks\nbei Fahrzeugen.","Voller Benzinkanister"},
		{"Medic Kit",2, 'chest.png', 128, 128, "Item", "<Das solltest du nicht haben.>","Verbandskasten","Use"},
		{"Heat Pack",1, 'heatpack.png', 128, 128, "Item", "Der Kristallisationsprozess beim Öffnen \nsorgt für die die nötige Wärme.","Wärmeflasche","Use"},
		{"Painkiller",1, 'painkillers.png', 128, 128, "Item", "Ein relativ wirksames Schmerzmittel\nzum Behandeln von Schmerzen und\nEntzündungen.","Schmerzmittel","Use"},
		{"Morphine",1, 'morphine.png',128,128,"Item", "Wird zum Behandeln von starken \nSchmerzen, zum Beispiel nach Brüchen,\ninjiziert.","Morphium","Use"},
		{"Blood Bag",1, 'bloodbag.png', 128, 85, "Item", "Blutbeutel zum Verabreichen einer\nBlutransfusion.","Blutbeutel","Use"},
		{"Wire Fence", 1, 'wirefence.png', 128, 128, "Item", "Rasiermesserscharfes Draht in Form\neines Zauns, perfekt um Angreifer\n abzuwehren.","Stacheldrahtzaun","Build a wire fence"}, 
		{"Raw Meat", 1, 'rawmeat.png', 128, 128,"Item", "Rohes Fleisch, direkt vom Tier\n geschlachtet.","Rohes Fleisch"}, 
		{"Tire", 2, 'wheel.png', 128, 128,"Item", "Ein alter Reifen. Kann zum Reparieren\n von Fahrzeugen genutzt werden.","Reifen"}, 
		{"Engine", 5, 'engine.png', 128,128,"Item", "Motorteile und Motoröl. Alles, was man\nbraucht, um ein Fahrzeug wieder\n flott zu kriegen.","Motor"},
		{"Tank Parts", 3, 'engine_part.png', 128,128,"Item", "Benzintankteile zum Reparieren\neines Fahrzeugs mit beschädigtem Tank.","Benzintankteile"},
		{"Main Rotary Parts", 6, 'rotary.png', 128, 128,"Item", "Rotorteile für einen Heli.","Rotorteile"}, 
		{"Scrap Metal", 3, 'parts.png', 128,128,"Item", "Altes Metall, kann zum Reparieren\nvon Fahrzeugen genutzt werden.","Altes Metall"},
		{"Windscreen Glass", 2, 'glass.png', 128, 128,"Item", "Eine Windschutzscheibe.","Windschutzscheibe"}, 		
		{"Tent", 3, 'tent.png', 128, 128, "Item", "Ein Zelt zum sicheren Verwahren\n deiner gesammelten Items.","Zelt","Pitch a tent"}, 
		{"Camouflage Clothing",1,'clothes.png',128,128,"Item","Mixtur aus Kleidung in Tarnfarben,\nohne Hut. Kann getragen werden.","Tarnfarbenkleidung","Put clothes on"},
		{"Civilian Clothing",1,'clothes.png',128,128,"Item","Zivile Kleidung mit Weste und Käppi.","Zivile Kleidung","Put clothes on"},
		{"Survivor Clothing",1,'clothes.png',128,128,"Item","Normale Kleidung. Kann getragen werden.","Überlebenskleidung","Put clothes on"},
		{"Civilian Clothing (Female)",1,'clothes.png',128,128,"Item","Zivile Kleidung mit Weste und Käppi.\nFür Frauen.","Zivile Kleidung (F)","Put clothes on"},
		{"Survivor Clothing (Female)",1,'clothes.png',128,128,"Item","Normale Kleidung, nur für Frauen.\nKann getragen werden.","Survivor Clothing (F)","Put clothes on"},
		{"Ghillie Suit",1,'clothes.png',128,128,"Item","Ein spezieller Anzug, mit dem man\nfast perfekt mit der Natur verschmilzt.","Ghillie-Anzug","Put clothes on"},
		{"Empty Water Bottle", 1, 'emptybottle.png', 128, 128,"Item", "Eine Flasche gefiltertes Wasser.\nIst allerdings leer.","Wasserflasche (Leer)", "Fill bottle up"}, 
		{"Empty Soda Can", 1,'emptysoda.png', 128, 128,"Item", "Enthielt einst ein köstliches Getränk,\nist jetzt aber leer und kaputt.","Leere Getränkedose"}, 
		{"Assault Pack (ACU)",1,'acu.png',170,170,"Item", "Erhöht Slotanzahl auf 12.","Assault Pack (ACU)"},
		{"Czech Vest Pouch",1,'czechpouch.png',170,170,"Item", "Erhöht Slotanzahl auf 13.","Czech Vest Pouch"},
		{"ALICE Pack",1,'alice.png',170,170,"Item", "Erhöht Slotanzahl auf 16.","ALICE Pack"},
		{"Survival ACU",1,'survival.png',170,170,"Item", "Erhöht Slotanzahl auf 17.","Survival ACU"},
		{"British Assault Pack",1,'britishpack.png',170,170,"Item", "Erhöht Slotanzahl auf 18.","British Assault Pack"},
		{"Backpack (Coyote)",1,'coyote.png',170,170,"Item", "Erhöht Slotanzahl auf 24.","Backpack (Coyote)"},
		{"Czech Backpack",1,'czech.png',170,170,"Item", "Erhöht Slotanzahl auf 30.","Czech Backpack"},
		{"San Fierro Carrier Keycard",1,'keycard.png',170,170,"Item","Allows you to open the door\nin the San Fierro Carrier.\nIs consumed after use.","SF Carrier Keycard","Activate"},
		{"Area 69 Keycard",1,'keycard.png',170,170,"Item","Allows you to open the door\nin Area 69.\nIs consumed after use.","Area 69 Keycard","Activate"},
		{"M4 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nNägel(x2)","M4 Blaupause","Craft"},
		{"CZ 550 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nGläser(x1)","CZ 550 Blaupause","Craft"},
		{"Winchester '66 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x2)\nGewehrschaft(x1)\nKlebeband(x4)","Winchester '66 Blaupause","Craft"},
		{"SPAZ-12 C. Shtgn. Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x2)\nGewehrschaft(x1)\nKlebeband(x4)","SPAZ-12 Kampfschr. Blaupause","Craft"},
		{"Sawn-Off Shtgn. Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x2)\nGewehrschaft(x2)\nKlebeband(x2)","Abgesägte Schr. Blaupause","Craft"},
		{"AK-47 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nNägel(x2)","AK-47 Blaupause","Craft"},
		{"Lee Enfield Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nKlebeband(x2)","Lee Enfield","Craft"},
		{"Sporter 22 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nKlebeband(x2)","Sporter 22 Blaupause","Craft"},
		{"Mosin 9130 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nKlebeband(x2)","Mosin 9130 Blaupause","Craft"},
		{"Crossbow Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x2)\nHandle(x1)\nHolzstab(x2)","Armbust Blaupause","Craft"},
		{"SKS Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nKlebeband(x2)","SKS Blaupause","Craft"},
		{"Blaze 95 D. R. Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x2)\nGewehrschaft(x1)\nKlebeband(x4)","Blaze 95. D. G. Blaupause","Craft"},
		{"Remington 870 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x2)\nGewehrschaft(x1)\nKlebeband(x4)","Remington 870 Blaupause","Craft"},
		{"FN FAL Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nNägel(x2)","FN FAL Blaupause","Craft"},
		{"G36C Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nNägel(x2)","G36C Blaupause","Craft"},
		{"Sa58V CCO Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nNägel(x2)","Sa58V CCO Blaupause","Craft"},
		{"SVD Dragunov Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nGläser(x1)","SVD Dragunov Blaupause","Craft"},
		{"DMR Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGewehrlauf(x1)\nGewehrschaft(x1)\nGläser(x1)","DMR Blaupause","Craft"},
		{"M1911 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\nNägel(x2)","M1911 Blaupause","Craft"},
		{"M9 SD Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\Metallstab(x1)","M9 SD Blaupause","Craft"},
		{"PDW Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\nNägel(x2)","PDW Blaupause","Craft"},
		{"G17 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\nKleber(x2)","G17 Blaupause","Craft"},
		{"MP5A5 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\nKlebeband(x2)","MP5A5 Blaupause","Craft"},
		{"Bizon PP-19 Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\nKlebeband(x2)","Bizon PP-19 Blaupause","Craft"},
		{"Revolver Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\nNägel(x3)","Revolver Blaupause","Craft"},
		{"Desert Eagle Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nPistolenlauf(x1)\nGewehrschaft(x1)\nNägel(x3)","Desert Eagle Blaupause","Craft"},
		{"Hunting Knife Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\Griff(x1)\nScharfes Metall(x1)\nKleber(x1)","Jadgmesser Blaupause","Craft"},
		{"Hatchet Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\Griff(x1)\nMetallplatte(x1)\nStacheldraht(x1)","Beil Blaupause","Craft"},
		{"Baseball Bat Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nHolzstab(x1)\nNägel(x1)\nKleber(x1)","Baseballschläger Blaupause","Craft"},
		{"Shovel Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nHolzstab(x1)\nMetallplatte(x1)\nNägel(x1)","Schaufel Blaupause","Craft"},
		{"Golf Club Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nMetallstab(x1)\nMetallplatte(x1)\nStacheldraht(x1)","Golfschläger Blaupause","Craft"},
		{"Machete Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\Griff(x1)\nScharfes Metall(x2)\nKleber(x2)","Machete Blaupause","Craft"},
		{"Crowbar Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nMetallstab(x1)\nHandsäge(x1)\nKlebeband(x1)","Brecheisen Blaupause","Craft"},
		{"Parachute Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nSchnur(x4)\nStoff(x2)\nLaken(x2)","Fallschirm Blaupause","Craft"},
		{"Tear Gas Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleber(x2)\nKleines Gehäuse(x1)\nFaden(x1)","Tränengas Blaupause","Craft"},
		{"Grenade Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x4)\nKabel(x1)","Granate Blaupause","Craft"},
		{"Binoculars Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGläser(x2)\nKleine Box(x1)\nKleber(x1)","Fernglas Blaupause","Craft"},
		{".45 ACP Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarpulver(x2)\nKleber(x1)",".45 ACP Patronen Blaupause","Craft"},
		{"9x19mm SD Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","9x19mm SD Patronen Blaupause","Craft"},
		{"9x19mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","9x19mm Patronen Blaupause","Craft"},
		{"9x18mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","9x18mm Patronen Blaupause","Craft"},
		{"5.45x39mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","5.45x39mm Patronen Blaupause","Craft"},
		{"5.56x45mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","5.56x45mm Patronen Blaupause","Craft"},
		{"1866 Slug Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","1866 Gewehrkugeln Blaupause","Craft"},
		{"2Rnd. Slug Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","2 Gewehrkugeln Blaupause","Craft"},
		{"12 Gauge Pellet Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","Kaliber 12 Schrot. Blaupause","Craft"},
		{"9.3x62mm Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)","9.3x62mm Patronen Blaupause","Craft"},
		{".303 British Cartridge Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleines Gehäuse(x1)\nSchwarzpulver(x2)\nKleber(x1)",".303 British Patronen Blaupause","Craft"},
		{"Bolt Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nHolzstab(x2)\nScharfes Metall(x2)\nHandsäge(x1)","Bolzen Blaupause","Craft"},
		{"Medic Kit Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nMedikamente(x2)\nVitamine(x2)\nPflaster(x1)","Verbandskasten Blaupause","Craft"},
		{"Wire Fence Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nStacheldraht(x1)\nHolzstab(x2)\nKlebeband(x1)","Stacheldrahtzaun Blaupause","Craft"},
		{"Tent Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nSchnur(x1)\nLaken(x2)\nHolzstab(x1)","Zelt Blaupause","Craft"},
		{"Camouflage Clthng. Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nFaden(x3)\nStoff(x1)\nNadel(x1)","Tarnfarbenkleidung Blaupause","Craft"},
		{"Survivor Clthng. Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nFaden(x3)\nStoff(x1)\nNadel(x1)","Überlebenskleidung Blaupause","Craft"},
		{"Civilian Clthng. Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nFaden(x3)\nStoff(x1)\nNadel(x1)","Zivile Kleidung Blaupause","Craft"},
		{"Ghillie Suit Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nFaden(x3)\nStoff(x3)\nNadel(x2)","Ghillie-Anzug Blaupause","Craft"},
		{"Road Flare Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nKleine Box(x1)\nSchwarzpulver(x1)\nTaschentuch(x1)","Leuchtfeuer Blaupause","Craft"},
		{"Toolbox Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nWerkzeuge(x1)\nKleine Box(x1)\nHandsäge(x1)","Werkzeugkasten Blaupause","Craft"},
		{"Radio Device Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nMikrochips(x2)\nKleine Box(x1)\nWerkzeuge(x1)","Radio Blaupause","Craft"},
		{"IR Goggles Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGläser(x3)\nMikrochips(x4)\nKleber(x1)","IR-Sichtgerät Blaupause","Craft"},
		{"NV Goggles Blueprint",1,'blueprint.png',128,128,"Blaupause","Komponenten:\nGläser(x3)\nMikrochips(x4)\nKleber(x1)","Nachtsichtgerät Blaupause","Craft"},
		{"Gun Barrel",1,'parts.png',128,128,"Used in:","Universelle Komponente für Primärwaffen.","Gewehrlauf"},
		{"Short Gun Barrel",1,'parts.png',128,128,"Used in:","Universelle Komponente für Sekundärwaffen.","Pistolenlauf"},
		{"Gun Stock",1,'parts.png',128,128,"Used in:","Universelle Komponente für alle Waffen.","Gewehrschaft"},
		{"Thread",1,'parts.png',128,128,"Used in:","Ein Faden. Was hast du erwartet?","Faden"},
		{"Cloth",1,'parts.png',128,128,"Component","Kann zum Herstellen verschiedenster\n Kleidungsstücke verwendet werden.","Stoff"},
		{"Gun Powder",1,'parts.png',128,128,"Component","Universelle Komponente für Munition.","Schwarzpulver"},
		{"Mechanical Supplies",1,'parts.png',128,128,"Component","Universelle Komponente für alles Mechanische.","Werkzeuge"},
		{"Cables",1,'parts.png',128,128,"Component","Universelle Komponente für alles Elektronische","Kabel"},
		{"Nails",1,'parts.png',128,128,"Component","Universelle Komponente für alles mögliche.","Nägel"},
		{"Sheet",1,'parts.png',128,128,"Component","Ein Laken.\nHast du etwas anderes erwartet?","Laken"},
		{"Barbed Wire",1,'parts.png',128,128,"Component","Wird für Verschiedenes verwendet.","Barbed Wire"},
		{"Duct Tape",1,'parts.png',128,128,"Component","Extrastarkes Klebeband.","Klebeband"},
		{"Glue",1,'parts.png',128,128,"Component","Schnellhaftender Kleber.","Kleber"},
		{"Drugs",1,'parts.png',128,128,"Component","Wird für medizinische Ausrüstung benötigt.","Medikamente"},
		{"Bandaid",1,'parts.png',128,128,"Component","Wird für medizinische Ausrüstung benötigt.","Pflaster"},
		{"Vitamins",1,'parts.png',128,128,"Component","Wird für medizinische Ausrüstung benötigt.","Vitamine"},
		{"Tissue",1,'parts.png',128,128,"Component","Wird für medizinische Ausrüstung benötigt.","Taschentuch"},
		{"Small Box",1,'parts.png',128,128,"Component","Eine kleine Box.","Small Box"},
		{"String",1,'parts.png',128,128,"Component","Eine recht lange Schnur.","Schnur"},
		{"Needle",1,'parts.png',128,128,"Component","Wird zum Nähen verwendet.","Nadel"},
		{"Microchips",1,'parts.png',128,128,"Component","Kann für elektronische Gegenstände\nverwendet werden.","Mikrochips"},
		{"Optics",1,'parts.png',128,128,"Component","Zurechtgeschnittenes Fensterglas.","Gläser"},
		{"Sharp Metal",1,'parts.png',128,128,"Component","Ein Stück scharfes Metall.\nIst aber nicht scharf genug,\num als Waffe verwendet zu werden.","Scharfes Metall"},
		{"Handle",1,'parts.png',128,128,"Component","Ein sauber geformter Griff.","Griff"},
		{"Wooden Stick",1,'parts.png',128,128,"Component","Irgendein Holzstab,\nzufällig irgendwo gefunden.","Holzstab"},
		{"Hand Saw",1,'parts.png',128,128,"Component","Eine praktische Handsäge zum Mitnehmen.","Handsäge"},
		{"Metal Plate",1,'parts.png',128,128,"Component","Eine sehr schwere Metallplatte.","Metallplatte"},
		{"Metallic Stick",1,'parts.png',128,128,"Component","Ein sehr kurzer Metallstab.","Metallstab"},
		{"Small Casing",1,'parts.png',128,128,"Component","Ein kleines Gehäuse zum\n Verstauen von Gegenständen.","Kleines Gehäuse"},
	},

	["Toolbelt"] = {
		{"NV Goggles", 1,'nvgoggles.png',128,128,"Item", "Drücke 'N' zum Aktivieren.","Nachtsichtgerät"}, 
		{"IR Goggles", 1,'nvgoggles.png',128,128,"Item", "Drücke 'I' zum Aktivieren.","IR-Sichtgerät"}, 
		{"Map", 1,'map.png',128,128,"Item", "Drücke 'F11' zum Aktivieren.","Karte"}, 
		{"Box of Matches", 1, 'matchbox.png',100,100,"Item", "In Kombination mit einem Holzstapel\nkannst du ein hübsches Feuer entfachen.","Streichholzschachtel", "Make a Fire"}, 
		{"Watch", 1,'watch.png',128,128,"Item", "Zeigt die Uhrzeit an.","Uhr"}, 
		{"GPS", 1,'gps.png',128,128,"Item", "Zeigt dir, wo genau du gerade bist.","GPS"}, 
		{"Toolbox", 1,'toolbox.png',128,128,"Item", "Kann zum Reparieren aller\nmöglichen Fahrzeuge verwendet werden.","Werkzeugkasten"}, 
		{"Radio Device", 1,'radio.png',128,128,"Item", "Drücke 'Z' zum Aktivieren.","Radio"},
		{"Compass",1,'compass.png',128,128,"Item","Zeigt dir die Himmelsrichtungen an.","Kompass"},
	},

	},
	
["cs"] = {
["Weapons"] = {
		["Primary Weapon"] = {
			{"M4",10, 'm4.png', 256, 128,"Útočná puška", "Munice: Zásobník 5.56x45mm","M4"},
			{"CZ 550",10, 'cz550.png', 256,128,"Odstřelovačská puška", "Munice: Zásobník 9.3x62mm","CZ 550"},
			{"Winchester 1866",10, 'winchester.png', 256, 128 ,"Brokovnice", "Munice: Brok 1866","Winchester 1866"},
			{"SPAZ-12 Combat Shotgun",10, 'spaz.png', 256, 128 ,"Brokovnice", "Munice: Brok ráže 12","SPAZ-12 automatická brokovnice"},
			{"Sawn-Off Shotgun",10, 'sawn.png', 256, 128,"Brokovnice", "Munice: Pár broků","Upilovaná brokovnice"},
			{"AK-47",10, 'ak47.png', 256, 128 ,"Útočná puška", "Munice: Zásobník 5.45x39mm","AK-47"},
			{"Lee Enfield",10, 'enfield.png', 256, 128,"Opakovací puška", "Munice: Zásobník .303 British","Lee Enfield"},
			{"Sporter 22",10,'enfield.png',256,128,"Opakovací puška","Munice: Zásobník .303 British","Sporter 22"},
			{"Mosin 9130",10,'enfield.png',256,128,"Opakovací puška","Munice: Zásobník .303 British","Mosin 9130"},
			{"Crossbow",10,'crossbow.png',128,128,"Kuše","Munice: Čep","Sportovní kuše"},
			{"SKS",10,'enfield.png',256,128,"Opakovací puška","Munice: Zásobník .303 British","SKS"},
			{"Blaze 95 Double Rifle",10,'spaz.png',256,128,"Brokovnice","Munice: Pár broků","Blaze 95 dvouhlavňová brokovnice"},
			{"Remington 870",10,'remington.png',256,128,"Brokovnice","Munice: Brok ráže 12","Remington 870"},
			{"FN FAL",10,'fnfal.png',256,128,"Útočná puška","Munice: Zásobník 5.45x39mm","FN FAL"},
			{"G36C",10,'g36c.png',256,128,"Útočná puška","Munice: Zásobník 5.45x39mm","G36C"},
			{"Sa58V CCO",10,'sa58v.png',256,128,"Útočná puška","Munice: Zásobník 5.45x39mm","Sa58V CCO"},
			{"SVD Dragunov",10,'svd.png',256,128,"Odstřelovačská puška","Munice: Zásobník 9.3x62mm","SVD Dragunov"},
			{"DMR",10,'dmr.png',256,128,"Odstřelovačská puška","Munice: Zásobník 9.3x62mm","DMR"},
		},

		["Secondary Weapon"] = {
			{"M1911",5, 'm1911.png', 128, 128,"Pistole", "Munice: Zásobník .45 ACP","M1911"},
			{"M9 SD",5, 'm9sd.png', 128, 128,"Pistole", "Munice: Zásobník 9x19mm SD","M9 SD"},
			{"PDW",5, 'pdw.png', 128, 128,"Samopal", "Munice: Zásobník 9x19mm","UZI"},
			{"G17",5,'g17.png',128,128,"Pistole","Toto by jsi neměl mít.","G17"},
			{"MP5A5",5, 'mp5a5.png', 128, 128,"Samopal", "Munice: Zásobník 9x18mm","MP5A5"},
			{"Desert Eagle",5, 'revolver.png',128,128,"Pistole","Munice: Zásobník .45 ACP","Desert Eagle"},
			{"Bizon PP-19",5,'bizon.png',128,128,"Samopal","Munice: Zásobník 9x18mm","Bizon PP-19"},
			{"Revolver",5,'revolver.png',128,128,"Pistole","Munice: Zásobník .45 ACP","Revolver"},
			{"Hunting Knife",5, 'knife.png',128,128,"Zbraň na blízko", "Munice: Žádná","Lovecký nůž"},
			{"Hatchet",5, 'hatchet.png',128,128,"Zbraň na blízko", "Munice: Žádná","Sekera"},
			{"Baseball Bat",5, 'bat.png', 128,128,"Zbraň na blízko", "Munice: Žádná","Baseballová pálka"},
			{"Shovel",5, 'shovel.png', 128, 128,"Zbraň na blízko", "Munice: Žádná","Lopata"},
			{"Golf Club",5, 'golf.png', 128, 128,"Zbraň na blízko", "Munice: Žádná","Golfová hůl"},
			{"Crowbar",5, 'crowbar.png',128,128,"Zbraň na blízko","Munice: Žádná","Páčidlo"},
		},

		["Specially Weapon"] = {
			{"Parachute",1, 'parachute.png', 128,128,"Předmět", "Nasaď na záda pro použití.","Padák"},
			{"Tear Gas",1, 'gas.png', 128, 128,"Předmět", "Toto by jsi neměl mít.","Dýmovnice",},
			{"Grenade",5, 'grenade.png', 128, 128,"Předmět", "Extrémně smrtící a extrémně hlučný.","Granát",},
			{"Binoculars",1, 'binoculars.png', 128, 128,"Předmět", "Klikni pro nasazení.","Dalekohled"}
		},

	},

	["Ammo"] = {
		{".45 ACP Cartridge",0.085, '45acp.png',128,128,"Munice", "Pro:\nM1911\nDesert Eagle\nRevolver","Zásobník .45 ACP"},
		{"9x19mm SD Cartridge",0.085, '9x19sd.png',128,128,"Munice", "Pro:\nM9 SD","Zásobník 9x19mm SD"},
		{"9x19mm Cartridge",0.025, '9x19.png',128,128,"Munice", "Pro:\nUZI","Zásobník 9x19mm"},
		{"9x18mm Cartridge",0.025, '9x18.png',128,128,"Munice", "Pro:\nMP5A5\nBizon PP-19","Zásobník 9x18mm"},
		{"5.45x39mm Cartridge",0.035, 'ak.png',128,128,"Munice", "Pro:\nAK-47\nG36C\nFN FAL","Zásobník 5.45x39mm"},
		{"5.56x45mm Cartridge",0.035, 'm4.png',128,128,"Munice", "Pro:\nM4","Zásobník 5.56x45mm"},
		{"1866 Slug",0.067, 'shotgun.png',128,128,"Munice", "Pro:\nWinchester 1866","Krabice broků 1866"},
		{"2Rnd. Slug",0.067, 'shotgun.png',128,128,"Munice", "Pro:\nUpilovaná brokovnice\nBlaze 95 dvouhlavňová brokovnice","Pár broků"},
		{"12 Gauge Pellet",0.067, 'shotgun.png',128,128,"Munice", "Pro:\nSPAZ-12 a. brokovnice\nRemington 870","Krabice broků ráže 12"},
		{"9.3x62mm Cartridge",0.1, 'sniper.png',128,128,"Munice", "Pro:\nCZ 550\nDMR\nSVD Dragunov","Zásobník 9.3x62mm"},
		{".303 British Cartridge",0.1, 'british.png',128,128,"Munice", "Pro:\nLee Enfield\nSporter 22\nMosin 9130\nSKS","Zásobník .303 British"},
		{"Bolt",0.1,'arrow.png',128,128,"Munice","Pro:\nSportovní kuše","Čep"},
	},

	["Food"] = {
		{"Baked Beans",1,'bakedbeans.png',128,128,"Jídlo", "Pečené fazole v plechovce.\nDobře skladované mohou vydržet\npřes 5 let.","Pečené fazole",},
		{"Pasta",1,'pasta.png',128,128,"Jídlo", "Těstoviny v plechovce.\nDobře skladované mohou vydržet\npřes 5 let.","Těstoviny"},
		{"Sardines",1,'sardines.png',128,128,"Jídlo", "Sardinky v plechovce.\nDobře skladované mohou vydržet\npřes 5 let.","Sardinky"},
		{"Frank & Beans",1,'frankbeans.png',128,128,"Jídlo","Frank & Beans v plechovce.\nDobře skladované mohou vydržet\npřes 5 let.","Frank & Beans"},
		{"Can (Corn)",1,'corn.png',128,128,"Jídlo", "Neotevřená plechovka s kukuřicí.","Plechovka (Kukuřice)"},
		{"Can (Peas)",1,'peas.png',128,128,"Jídlo", "Neotevřená plechovka s hráškem.","Plechovka (Hrášek)"},
		{"Can (Pork)",1,'pork.png',128,128,"Jídlo", "Neotevřená plechovka s vepřovým masem.", "Plechovka (Vepřové maso)"},
		{"Can (Stew)",1,'stew.png',128,128,"Jídlo", "Neotevřená plechovka s dušeným hovězím masem.", "Plechovka (Hovězí maso)"},
		{"Can (Ravioli)",1,'ravioli.png',128,128,"Jídlo", "Neotevřená plechovka s těstovinami ravioli.", "Plechovka (Ravioli)"},
		{"Can (Fruit)",1,'fruit.png',128,128,"Jídlo", "Neotevřená plechovka s mixem ovoce.", "Plechovka (Ovoce)"},
		{"Can (Chowder)",1,'chowder.png',128,128,"Jídlo", "Neotevřená plechovka se škeblí polévkou.", "Plechovka (Polévka)"},
		{"MRE",1,'mre.png', 128, 128,"Jídlo", "Konzervovaná Dávka Potravin.","KDP"},
		{"Pistachios",1,'pistachios.png', 128, 128,"Jídlo", "Balíček pečených a solených pistácií.","Pistácie"},
		{"Trail Mix",1,'trailmix.png', 128, 128,"Jídlo", "Obashuje dvanáct druhů ovoce a ořechy.","Ovocný mix"},
		{"Cooked Meat",1, 'cookedmeat.png',128,128,"Jídlo", "Maso opečené na ohni.","Pečené maso"},
		{"Water Bottle",1, 'bottle.png', 128, 128,"Pití", "Láhev filtrované vody.","Láhev vody"},
		{"Soda Can (Pepsi)",1,'pepsi.png', 128, 128,"Pití", "Hliněná plechovka obsahující ochucený,\nnápoj plný cukru a umělých aromat.","Sodovka (Pepsi)"},
		{"Soda Can (Cola)",1,'cola.png', 128, 128,"Pití", "Hliněná plechovka obsahující ochucený,\nnápoj plný cukru a umělých aromat.","Sodovka (Cola)"},
		{"Soda Can (Mountain Dew)",1,'dew.png', 128, 128,"Pití", "Hliněná plechovka obsahující ochucený,\nnápoj plný cukru a umělých aromat.", "Sodovka (Mountain Dew)"},
		{"Can (Milk)",1,'milkcan.png',128,128,"Pití", "Hliněná plechovka obsahující mléko.", "Plechovka (Mléko)"},
	},

	["Items"] = {
		{"Wood Pile",2, 'wood.png',128,128,"Předmět", "Čerstvě nasbíraná hromádka\ndříví, lze použít například\nk založení ohniště.","Dříví"},
		{"Bandage",1, 'bandage.png', 128, 128, "Předmět", "Obvaz pro zastavení krvácení.","Obvaz","Bandage yourself"},
		{"Road Flare",1, 'roadflare.png', 128, 128, "Předmět", "Ručně aktivovatelná světlice, většinou\nse nachází ve vojenských výbavách.\nHoří kolem 5ti minut.","Světlice","Place"},
		{"Empty Gas Canister",3, 'canister.png', 128, 128,"Předmět", "20L kanistr k uskladnění paliv.\nSlouží k přečerpávání paliva do vozidel.\nTento kanistr je prázdný.","Prázdný kanistr"},
		{"Full Gas Canister",3, 'canister.png', 128, 128,"Předmět", "20L kanistr k uskladnění paliv.\nSlouží k přečerpávání paliva do vozidel.","Plný kanistr benzínu"},
		{"Medic Kit",2, 'chest.png', 128, 128, "Předmět", "Toto by jsi neměl mít.","Lékárnička","Použít"},
		{"Heat Pack",1, 'heatpack.png', 128, 128, "Předmět", "Termopolštářek sloužící k zateplení.\nPoužívá se k zahřátí po omrzlinách.","Termopolštářek","Use"},
		{"Painkiller",1, 'painkillers.png', 128, 128, "Předmět", "Lék proti bolesti.\nSlouží především ke stimulaci\nbolestí hlavy.","Lék proti bolesti","Use"},
		{"Morphine",1, 'morphine.png',128,128,"Předmět", "Používá se jako intramuskulární injekce\npro uklidnění silné bolesti, jako\nnapříklad od zlomeniny.","Morfium","Use"},
		{"Blood Bag",1, 'bloodbag.png', 128, 85, "Předmět", "Balení naplněné krví\nslouží k transfuzi krve.","Krevní vak","Use"},
		{"Wire Fence", 1, 'wirefence.png', 128, 128, "Předmět", "Ostnatý drát ve velkých kolách,\nkterý může být rozšířen jako harmonika.\nČasto používáno armádou jako překážka.","Ostnatý drát","Build a wire fence"}, 
		{"Raw Meat", 1, 'rawmeat.png', 128, 128,"Předmět", "Syrové zvířecí maso.","Syrové maso"}, 
		{"Tire", 2, 'wheel.png', 128, 128,"Předmět", "Staré kolo od auta, lze\npoužít jako náhradní kolo u vozidel.","Kolo"}, 
		{"Engine", 5, 'engine.png', 128,128,"Předmět", "Součásti motoru s olejem a mazivem.\nVše potřebné k opravě motoru.","Motor"}, 
		{"Tank Parts", 3, 'engine_part.png', 128,128,"Předmět", "Díly nádrže k opravě nádrže\nu vozidla s poškozenou nádrží.","Díly nádrže"},
		{"Tent", 3, 'tent.png', 128, 128, "Předmět", "Stan s provazy a hřebíky.\nLze snadno postavit a použít k\npřespání a skladování předmětů.","Stan","Pitch a tent"}, 
		{"Main Rotary Parts", 6, 'rotary.png', 128, 128,"Item", "Parts for a helicopter.","Main Rotary Parts"}, 
		{"Scrap Metal", 3, 'parts.png', 128,128,"Item", "Old metal, can be used to\n to repair vehicles.","Scrap Metal"},
		{"Windscreen Glass", 2, 'glass.png', 128, 128,"Item", "A windscreen glass for a vehicle.","Windscreen Glass"}, 	
		{"Camouflage Clothing",1,'clothes.png',128,128,"Předmět","Set maskované vojenské\nuniformy s lehkou výbavou a helmou.\nLze rozbalit a obléct.","Vojenská uniforma","Put clothes on"},
		{"Civilian Clothing",1,'clothes.png',128,128,"Předmět","Set klasických nošených kalhot\ns lehkou vestou a čepicí.\nLze rozbalit a obléct.","Civilní oblečení","Put clothes on"},
		{"Survivor Clothing",1,'clothes.png',128,128,"Předmět","Set lehkého oblečení pro snadný\npohyb, vhodné k přežití.\nLze rozbalit a obléct.","Přeživší oblečení","Put clothes on"},
		{"Civilian Clothing (Female)",1,'clothes.png',128,128,"Item","Set klasických nošených kalhot\ns lehkou vestou a čepicí.\nLze rozbalit a obléct.","Civilní oblečení (F)","Put clothes on"},
		{"Survivor Clothing (Female)",1,'clothes.png',128,128,"Item","Set lehkého oblečení pro snadný\npohyb, vhodné k přežití.\nLze rozbalit a obléct.","Přeživší oblečení (F)","Put clothes on"},
		{"Ghillie Suit",1,'clothes.png',128,128,"Předmět","Typ maskovaného oblečení, vytvořeného k\ndokonalé kamufláži. Nikdo vás neuvidí přicházet.\nLze rozbalit a obléct.","Maskování Hejkal","Put clothes on"},
		{"Empty Water Bottle", 1, 'emptybottle.png', 128, 128,"Předmět", "Láhev filtrované vody.\nMomentálně je prázdná.\nLze naplnit a vyfiltrovat u řeky.","Prázdná láhev", "Fill bottle up"}, 
		{"Empty Soda Can", 1,'emptysoda.png', 128, 128,"Předmět", "Prázdná hliněná plechovka.","Prázdná plechovka"}, 
		{"Assault Pack (ACU)",1,'acu.png',170,170,"Předmět", "Přidává +12 slotů inventáře.","Vojenský batoh"},
		{"Czech Vest Pouch",1,'czechpouch.png',170,170,"Předmět", "Přidává +13 slotů inventáře.","Sumka"},
		{"ALICE Pack",1,'alice.png',170,170,"Předmět", "Přidává +16 slotů inventáře.","Batoh ALICE"},
		{"Survival ACU",1,'survival.png',170,170,"Předmět", "Přidává +17 slotů inventáře.","Velký vojenský batoh"},
		{"British Assault Pack",1,'britishpack.png',170,170,"Předmět", "Přidává +18 slotů inventáře.","Britský vojenský batoh"},
		{"Backpack (Coyote)",1,'coyote.png',170,170,"Předmět", "Přidává +24 slotů inventáře.","Batoh Coyote"},
		{"Czech Backpack",1,'czech.png',170,170,"Předmět", "Přidává +30 slotů inventáře.","Český vojenský batoh"},
		{"San Fierro Carrier Keycard",1,'keycard.png',170,170,"Item","Allows you to open the door\nin the San Fierro Carrier.\nIs consumed after use.","SF Carrier Keycard","Activate"},
		{"Area 69 Keycard",1,'keycard.png',170,170,"Item","Allows you to open the door\nin Area 69.\nIs consumed after use.","Area 69 Keycard","Activate"},
		{"M4 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nHřebíky (x2)","Plánek k M4","Craft"},
		{"CZ 550 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nOptické sklo (x1)","Plánek k CZ 550","Craft"},
		{"Winchester '66 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x2)\nPažba (x1)\nLepící páska (x4)","Plánek k Winchester","Craft"},
		{"SPAZ-12 C. Shtgn. Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x2)\nPažba (x1)\nLepící páska (x4)","Plánek k SPAZ-12 a. brokovnici","Craft"},
		{"Sawn-Off Shtgn. Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x2)\nPažba (x2)\nLepící páska (x2)","Plánek k upilované brokovnici","Craft"},
		{"AK-47 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nHřebíky (x2)","Plánek k AK-47","Craft"},
		{"Lee Enfield Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nLepící páska (x2)","Plánek k Lee Enfield","Craft"},
		{"Sporter 22 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nLepící páska (x2)","Plánek k Sporter 22","Craft"},
		{"Mosin 9130 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nLepící páska (x2)","Plánek k Mosin 9130","Craft"},
		{"Crossbow Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x2)\nRukojeť (x1)\nDřevěná tyčka (x2)","Plánek k sportovní kuši","Craft"},
		{"SKS Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nLepící páska (x2)","Plánek k SKS","Craft"},
		{"Blaze 95 D. R. Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x2)\nPažba (x1)\nLepící páska (x4)","Plánek k Blaze 95. dh. brokovnici","Craft"},
		{"Remington 870 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x2)\nPažba (x1)\nLepící páska (x4)","Plánek k Remington 870","Craft"},
		{"FN FAL Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nHřebíky (x2)","Plánek k FN FAL","Craft"},
		{"G36C Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nHřebíky (x2)","Plánek k G36C","Craft"},
		{"Sa58V CCO Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nHřebíky (x2)","Plánek k Sa58V CCO","Craft"},
		{"SVD Dragunov Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nOptické sklo (x1)","Plánek k SVD Dragunov","Craft"},
		{"DMR Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nHlaveň (x1)\nPažba (x1)\nOptické sklo (x1)","Plánek k DMR","Craft"},
		{"M1911 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nHřebíky (x2)","Plánek k M1911","Craft"},
		{"M9 SD Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nKovová tyčka (x1)","Plánek k M9 SD","Craft"},
		{"PDW Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nHřebíky (x2)","Plánek k UZI","Craft"},
		{"G17 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nLepidlo (x2)","Plánek k G17","Craft"},
		{"MP5A5 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nLepící páska (x2)","Plánek k MP5A5","Craft"},
		{"Bizon PP-19 Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nLepící páska (x2)","Plánek k Bizon PP-19","Craft"},
		{"Revolver Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nHřebíky (x3)","Plánek k Revolveru","Craft"},
		{"Desert Eagle Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKrátká hlaveň (x1)\nPažba (x1)\nHřebíky (x3)","Plánek k Desert Eagle","Craft"},
		{"Hunting Knife Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nRukojeť (x1)\nOstrý kov (x1)\nLepidlo (x1)","Plánek k loveckému noži","Craft"},
		{"Hatchet Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nRukojeť (x1)\nKovový plát (x1)\nDrát (x1)","Plánek k sekeře","Craft"},
		{"Baseball Bat Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nDřevěná tyčka (x1)\nHřebíky (x1)\nLepidlo (x1)","Plánek k baseballové pálce","Craft"},
		{"Shovel Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nDřevěná tyčka (x1)\nKovový plát (x1)\nHřebíky (x1)","Plánek k lopatě","Craft"},
		{"Golf Club Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKovová tyčka (x1)\nKovový plát (x1)\nDrát (x1)","Plánek ke golfové holi","Craft"},
		{"Machete Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nRukojeť (x1)\nOstrý kov (x2)\nLepidlo (x2)","Plánek k mačetě","Craft"},
		{"Crowbar Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nKovová tyčka (x1)\nRuční pila (x1)\nLepící páska (x1)","Plánek k páčidlu","Craft"},
		{"Parachute Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nNiť (x4)\nLátka (x2)\nDeska (x2)","Plánek k padáku","Craft"},
		{"Tear Gas Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nLepidlo (x2)\nMalé pouzdro (x1)\nNiť (x1)","Plánek k dýmovnici","Craft"},
		{"Grenade Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x4)\nCables(x1)","Plánek k granátu","Craft"},
		{"Binoculars Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nOptické sklo (x2)\nMalá krabice (x1)\nLepidlo (x1)","Plánek k dalekohledu","Craft"},
		{".45 ACP Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici .45 ACP","Craft"},
		{"9x19mm SD Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici 9x19mm SD","Craft"},
		{"9x19mm Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici 9x19mm","Craft"},
		{"9x18mm Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici 9x18mm","Craft"},
		{"5.45x39mm Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici 5.45x39mm","Craft"},
		{"5.56x45mm Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici 5.56x45mm","Craft"},
		{"1866 Slug Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k broku 1866","Craft"},
		{"2Rnd. Slug Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k páru broků","Craft"},
		{"12 Gauge Pellet Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k brokům ráže 12","Craft"},
		{"9.3x62mm Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici 9.3x62mm","Craft"},
		{".303 British Cartridge Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalé pouzdro (x1)\nStřelný prach (x2)\nLepidlo (x1)","Plánek k munici .303 British","Craft"},
		{"Bolt Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nDřevěná tyčka (x2)\nOstrý kov (x2)\nRuční pila (x1)","Plánek k čepu","Craft"},
		{"Medic Kit Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nDrogy (x2)\nVitamíny (x2)\nNáplasti (x1)","Plánek k lékárničce","Craft"},
		{"Wire Fence Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nDrát (x1)\nDřevěná tyčka (x2)\nLepící páska (x1)","Plánek k ostnatému drátu","Craft"},
		{"Tent Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nNiť (x1)\nDeska (x2)\nDřevěná tyčka (x1)","Plánek ke stanu","Craft"},
		{"Camouflage Clthng. Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nPříze (x3)\nLátka (x1)\nJehla (x1)","Plánek k vojenské uniformě","Craft"},
		{"Survivor Clthng. Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nPříze (x3)\nLátka (x1)\nJehla (x1)","Plánek k přeživšímu oblečení","Craft"},
		{"Civilian Clthng. Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nPříze (x3)\nLátka (x1)\nJehla (x1)","Plánek k civilnímu oblečení","Craft"},
		{"Ghillie Suit Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nPříze (x3)\nLátka (x3)\nJehla (x2)","Plánek k maskování Hejkal","Craft"},
		{"Road Flare Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMalá krabice (x1)\nStřelný prach (x1)\nTkanina (x1)","Plánek ke světlici","Craft"},
		{"Toolbox Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMechanické zásoby (x1)\nMalá krabice (x1)\nRuční pila (x1)","Plánek k nářadí","Craft"},
		{"Radio Device Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nMicrochips(x2)\nMalá krabice (x1)\nMechanické zásoby (x1)","Plánek k vysílačce","Craft"},
		{"IR Goggles Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nOptické sklo (x3)\nMikročipy (x4)\nLepidlo (x1)","Plánek k termovizi","Craft"},
		{"NV Goggles Blueprint",1,'blueprint.png',128,128,"Plánek","Komponenty:\nOptické sklo (x3)\nMikročipy (x4)\nLepidlo (x1)","Plánek k noktovizi","Craft"},
		{"Gun Barrel",1,'parts.png',128,128,"Komponent","Komponent k tvorbě zbraní.","Hlaveň"},
		{"Short Gun Barrel",1,'parts.png',128,128,"Komponent","Komponent k tvorbě zbraní.","Krátká hlaveň"},
		{"Gun Stock",1,'parts.png',128,128,"Komponent","Komponent k tvorbě zbraní.","Pažba"},
		{"Thread",1,'parts.png',128,128,"Komponent","Plast s omotanou nití.","Příze"},
		{"Cloth",1,'parts.png',128,128,"Komponent","Lze použít k šití obleků.","Látka"},
		{"Gun Powder",1,'parts.png',128,128,"Komponent","Střelný prach, nutný pro tvorbu munice.","Střelný prach"},
		{"Mechanical Supplies",1,'parts.png',128,128,"Komponent","Univerzální komponent pro elektrospotřebiče.","Mechanické zásoby"},
		{"Cables",1,'parts.png',128,128,"Komponent","Univerzální komponent pro elektrospotřebiče.","Kabely"},
		{"Nails",1,'parts.png',128,128,"Komponent","Univerzální předmět potřebný pro řadu věcí.","Hřebíky"},
		{"Sheet",1,'parts.png',128,128,"Komponent","Malá deska.","Deska"},
		{"Barbed Wire",1,'parts.png',128,128,"Komponent","Dlouhý drát s ostny po obvodu.","Drát"},
		{"Duct Tape",1,'parts.png',128,128,"Komponent","Univerzální páska k lepení.","Lepící páska"},
		{"Glue",1,'parts.png',128,128,"Komponent","Univerzální prostředek k lepení.","Lepidlo"},
		{"Drugs",1,'parts.png',128,128,"Komponent","Určeno pro lékařské využití.","Drogy"},
		{"Bandaid",1,'parts.png',128,128,"Komponent","Určeno pro lékařské využití.","Náplasti"},
		{"Vitamins",1,'parts.png',128,128,"Komponent","Určeno pro lékařské využití.","Vitamíny"},
		{"Tissue",1,'parts.png',128,128,"Komponent","Určeno pro lékařské využití.","Tkanina"},
		{"Small Box",1,'parts.png',128,128,"Komponent","Malá krabice ve tvaru krychle.","Malá krabice"},
		{"String",1,'parts.png',128,128,"Komponent","Dlouhá niť.","Niť"},
		{"Needle",1,'parts.png',128,128,"Komponent","Velice ostrá jehla na šití.","Jehla"},
		{"Microchips",1,'parts.png',128,128,"Komponent","Použito v elektrospotřebičích.","Mikročipy"},
		{"Optics",1,'parts.png',128,128,"Komponent","Lze použít například k\ntvorbě dalekohledů.","Optické sklo"},
		{"Sharp Metal",1,'parts.png',128,128,"Komponent","Ostrý kus kovu, bohužel\nne dostatečně ostrý, aby\nse dal použít jako zbraň.","Ostrý kov"},
		{"Handle",1,'parts.png',128,128,"Komponent","Rukojeť pro zbraně v dobrém stavu.","Rukojeť"},
		{"Wooden Stick",1,'parts.png',128,128,"Komponent","Náhodný nalezený dřevěný klacík.","Dřevená tyčka"},
		{"Hand Saw",1,'parts.png',128,128,"Komponent","Běžně používaná na stavbách.","Ruční pila"},
		{"Metal Plate",1,'parts.png',128,128,"Komponent","Velice tvrdý kovový plát.","Kovový plát"},
		{"Metallic Stick",1,'parts.png',128,128,"Komponent","Kovová tyčka, je velice\nkrátká. Lze použít k\nsestavení zbraní.","Kovová tyčka"},
		{"Small Casing",1,'parts.png',128,128,"Komponent","Malé pouzdro k uskladnění věcí.","Malé pouzdro"},
	},

	["Toolbelt"] = {
		{"NV Goggles", 1,'nvgoggles.png',128,128,"Předmět", "Stiskni 'N' pro aktivaci.","Noční vidění"}, 
		{"IR Goggles", 1,'nvgoggles.png',128,128,"Předmět", "Stiskni 'I' pro aktivaci.","Termovize"}, 
		{"Map", 1,'map.png',128,128,"Předmět", "Stiskni 'F11' pro aktivaci.","Mapa"}, 
		{"Box of Matches", 1, 'matchbox.png',100,100,"Předmět", "Použij v kombinaci se dřívím\nk založení ohniště.","Krabička sirek", "Make a Fire"}, 
		{"Watch", 1,'watch.png',128,128,"Předmět", "Pasivní předmět, je\naktivován sebráním.","Hodinky"}, 
		{"GPS", 1,'gps.png',128,128,"Předmět", "Pasivní předmět, je\naktivován sebráním.","GPS"}, 
		{"Toolbox", 1,'toolbox.png',128,128,"Předmět", "Nařadí sloužící k\nopravě různých druhů vozidel.","Nářadí"}, 
		{"Radio Device", 1,'radio.png',128,128,"Předmět", "Stiskni 'Z' pro aktivac.","Vysílačka"},
		{"Compass",1,'compass.png',128,128,"Předmět","Pasivní předmět, je\naktivován sebráním.","Kompas"},
	},
},
}